"""Curated phrase-to-tag aliases for abstract vibe matching."""

from __future__ import annotations


VIBE_ALIASES = {
    "desert": ["desert", "arid", "sand", "sunbaked", "cactus", "dry heat", "mineral", "sage"],
    "dessert": ["vanilla", "tonka bean", "cocoa", "sweet", "gourmand", "comforting"],
    "dunes": ["desert", "sand", "sunbaked", "dry", "mineral", "warm"],
    "canyon": ["desert", "mineral", "dry", "cedar", "sunbaked", "earthy"],
    "chaparral": ["sage", "dry", "herbal", "sunbaked", "green", "earthy"],
    "mountain": ["pine", "cedar", "fresh air", "cold", "forest", "mineral"],
    "forest": ["forest", "pine", "oakmoss", "mossy", "earthy", "green", "cedar"],
    "library": ["paper", "cedar", "quiet", "powdery", "nostalgic", "dry"],
    "classroom": ["paper", "cedar", "morning", "clean", "nostalgic", "quiet"],
    "school": ["paper", "cedar", "morning", "clean", "nostalgic", "quiet"],
    "early classroom": ["paper", "morning", "quiet", "clean", "sunrise", "nostalgic"],
    "classroom morning": ["paper", "morning", "sunrise", "clean", "nostalgic", "cedar"],
    "job interview": ["confident", "polished", "white shirt", "clean", "cedar", "bergamot", "musk"],
    "interview": ["confident", "polished", "white shirt", "clean", "cedar", "bergamot"],
    "first day": ["anxious", "hopeful", "clean", "white shirt", "bergamot", "cedar"],
    "office": ["polished", "white shirt", "clean", "cedar", "minimal", "confident"],
    "spring": ["spring", "green", "peony", "cherry blossom", "fresh", "rain"],
    "summer": ["summer", "coconut water", "sea salt", "citrus", "bright", "beach"],
    "autumn": ["autumn", "fall", "cedar", "amber", "cocoa", "dry", "spicy"],
    "fall": ["fall", "autumn", "cedar", "amber", "cocoa", "dry", "spicy"],
    "winter": ["winter", "snow", "frost", "cold", "pine", "vanilla", "musk"],
    "snow": ["snow", "frost", "cold", "clean", "musk", "pine"],
    "rainy": ["rain", "petrichor", "fresh air", "melancholy", "green"],
    "humid": ["humid", "tropical", "jasmine", "green", "coconut water", "marine"],
    "dry season": ["dry season", "dry", "sunbaked", "cedar", "vetiver", "desert"],
    "red": ["red", "rose", "pink pepper", "plum", "spicy", "romantic", "bold"],
    "pink": ["pink", "peony", "cherry blossom", "rose", "soft", "flirty"],
    "orange": ["orange", "mandarin", "neroli", "citrus", "bright", "warm"],
    "yellow": ["yellow", "lemon", "honey", "bright", "sunlit", "happy"],
    "gold": ["gold", "golden", "amber", "honey", "saffron", "luxury", "warm"],
    "green": ["green", "fig leaf", "basil", "matcha", "forest", "herbal"],
    "blue": ["blue", "cool", "marine", "rain", "melancholy", "ozone", "sad"],
    "navy": ["navy", "night", "marine", "mysterious", "amber", "clean"],
    "purple": ["purple", "violet", "iris", "plum", "dreamy", "powdery"],
    "violet": ["violet", "iris", "powdery", "soft", "nostalgic", "floral"],
    "black": ["black", "dark", "smoke", "leather", "incense", "patchouli"],
    "white": ["white", "clean", "musk", "white shirt", "neroli", "snow"],
    "silver": ["silver", "aldehydes", "metallic", "futuristic", "clean", "ozone"],
    "grey": ["grey", "gray", "rain", "musk", "concrete", "muted", "mineral"],
    "gray": ["gray", "grey", "rain", "musk", "concrete", "muted", "mineral"],
    "brown": ["brown", "cedar", "cocoa", "tonka bean", "earthy", "warm"],
    "cream": ["cream", "vanilla", "sandalwood", "milk accord", "soft", "comforted"],
    "clear": ["clear", "clean", "water", "ozone", "minimal", "fresh"],
    "neon": ["neon", "electric", "metallic", "grapefruit", "pink pepper", "futuristic"],
    "pastel": ["pastel", "soft", "powdery", "peony", "cherry blossom", "airy"],
    "black velvet": ["black", "velvet", "plum", "incense", "rose", "dark"],
    "white winter": ["white", "winter", "snow", "musk", "clean", "frost"],
    "sad": ["sad", "melancholy", "lonely", "quiet", "muted", "rain", "iris", "violet", "musk"],
    "depressed": ["sad", "melancholy", "quiet", "muted", "rain", "comforted"],
    "lonely": ["lonely", "quiet", "skin", "musk", "rain", "night"],
    "heartbroken": ["heartbroken", "sad", "rose", "iris", "smoke", "velvet"],
    "grief": ["grief", "incense", "smoke", "iris", "mossy", "dark"],
    "nostalgic": ["nostalgic", "bittersweet", "powdery", "iris", "violet", "vanilla"],
    "bittersweet": ["bittersweet", "orange", "rose", "amber", "soft"],
    "hopeful": ["hopeful", "sunrise", "neroli", "bergamot", "green", "clean"],
    "happy": ["happy", "joyful", "bright", "sparkling", "citrus", "fresh"],
    "joyful": ["joyful", "bright", "sparkling", "orange blossom", "peony", "fresh"],
    "euphoric": ["euphoric", "sparkling", "pink pepper", "grapefruit", "luminous"],
    "peaceful": ["peaceful", "calm", "lavender", "tea", "clean", "soft"],
    "calm": ["calm", "green tea", "lavender", "quiet", "spa", "clean"],
    "anxious": ["anxious", "restless", "ginger", "peppery", "ozone", "electric"],
    "restless": ["restless", "night drive", "ozone", "ginger", "metallic"],
    "angry": ["angry", "bold", "smoke", "leather", "peppery", "dark"],
    "confident": ["confident", "bold", "saffron", "leather", "luxury", "cedar"],
    "sensual": ["sensual", "skin", "amber", "vanilla", "jasmine", "sandalwood"],
    "dreamy": ["dreamy", "soft focus", "luminous", "musk", "iris", "airy"],
    "mysterious": ["mysterious", "incense", "dark", "smoke", "labdanum", "night"],
    "comforted": ["comforted", "comforting", "vanilla", "tonka bean", "cocoa", "soft"],
    "vulnerable": ["vulnerable", "skin", "musk", "quiet", "soft", "iris"],
}
