"""Seed note definitions for the local scent catalog."""

from __future__ import annotations


NOTE_SEEDS = [{'name': 'Aldehydes',
  'role': 'top',
  'description': 'Sparkling and polished with a metallic lift.',
  'fallback': 1,
  'tags': ['robotic', 'futuristic', 'clean', 'bright', 'sunrise', 'silver', 'polished']},
 {'name': 'Metallic Accord',
  'role': 'top',
  'description': 'An industrial, chrome-like shimmer with a city edge.',
  'fallback': 0,
  'tags': ['robotic', 'metallic', 'industrial', 'city lights', 'futuristic', 'glossy']},
 {'name': 'Ozone',
  'role': 'top',
  'description': 'Charged air that feels like rain before the storm.',
  'fallback': 1,
  'tags': ['fresh air', 'electric', 'rain', 'night drive', 'skyline', 'clean']},
 {'name': 'Bergamot',
  'role': 'top',
  'description': 'Bright citrus with a crisp, lifted opening.',
  'fallback': 1,
  'tags': ['sunrise', 'bright', 'citrus', 'city lights', 'energetic', 'sparkling', 'clean']},
 {'name': 'Grapefruit Zest',
  'role': 'top',
  'description': 'Sharp, juicy citrus with a playful edge.',
  'fallback': 0,
  'tags': ['bright', 'citrus', 'sporty', 'sunrise', 'fresh', 'uplifting']},
 {'name': 'Lemon Peel',
  'role': 'top',
  'description': 'A clean lemon snap that feels bright and airy.',
  'fallback': 0,
  'tags': ['bright', 'sparkling', 'clean', 'daylight', 'uplifting', 'citrus']},
 {'name': 'Pink Pepper',
  'role': 'top',
  'description': 'Flirty sparkle with a modern peppery bite.',
  'fallback': 0,
  'tags': ['romantic', 'modern', 'sparkling', 'night out', 'flirty', 'peppery']},
 {'name': 'Cardamom',
  'role': 'heart',
  'description': 'Warm spice with a smooth, stylish finish.',
  'fallback': 1,
  'tags': ['spicy', 'warm spice', 'night out', 'sophisticated', 'bold', 'smooth']},
 {'name': 'Ginger',
  'role': 'top',
  'description': 'Zesty energy with a lively, modern twist.',
  'fallback': 0,
  'tags': ['spicy', 'zesty', 'energetic', 'modern', 'bold', 'daylight']},
 {'name': 'Green Tea',
  'role': 'heart',
  'description': 'Soft, minimalist freshness with a quiet calm.',
  'fallback': 1,
  'tags': ['calm', 'minimal', 'quiet', 'clean', 'soft', 'tea', 'green']},
 {'name': 'Mint',
  'role': 'top',
  'description': 'Cool and crisp with a clean morning vibe.',
  'fallback': 0,
  'tags': ['cool', 'fresh', 'clean', 'morning', 'crisp', 'green']},
 {'name': 'Eucalyptus',
  'role': 'top',
  'description': 'Spa-like freshness that clears the room.',
  'fallback': 0,
  'tags': ['spa', 'fresh air', 'calm', 'clean', 'minimal', 'fresh']},
 {'name': 'Neroli',
  'role': 'heart',
  'description': 'Sunlit citrus blossom with a tailored finish.',
  'fallback': 1,
  'tags': ['sunlit', 'white shirt', 'clean', 'romantic', 'bright', 'citrus', 'floral']},
 {'name': 'Pear Skin',
  'role': 'top',
  'description': 'Soft fruit with a modern, airy feel.',
  'fallback': 0,
  'tags': ['soft', 'modern', 'airy', 'romantic', 'fresh', 'bright']},
 {'name': 'Violet Leaf',
  'role': 'heart',
  'description': 'Cool green with a muted, rainy elegance.',
  'fallback': 0,
  'tags': ['rain', 'cool', 'green', 'muted', 'fresh', 'botanical']},
 {'name': 'Rose',
  'role': 'heart',
  'description': 'Classic romantic bloom with velvet softness.',
  'fallback': 1,
  'tags': ['romantic', 'night out', 'soft', 'velvet', 'date night', 'floral']},
 {'name': 'Jasmine',
  'role': 'heart',
  'description': 'Glowing floral warmth for late evening energy.',
  'fallback': 1,
  'tags': ['romantic', 'glowing', 'night out', 'soft', 'floral', 'luminous']},
 {'name': 'Orange Blossom',
  'role': 'heart',
  'description': 'Clean floral sweetness with a polished glow.',
  'fallback': 0,
  'tags': ['romantic', 'sunlit', 'soft', 'clean', 'date night', 'floral']},
 {'name': 'Iris',
  'role': 'heart',
  'description': 'Powdery, elegant, and a little artistic.',
  'fallback': 0,
  'tags': ['powdery', 'elegant', 'artistic', 'romantic', 'cool', 'floral']},
 {'name': 'Lavender',
  'role': 'heart',
  'description': 'Quiet and calming with a clean nighttime feel.',
  'fallback': 1,
  'tags': ['calm', 'night', 'clean', 'quiet', 'soft', 'floral', 'herbal']},
 {'name': 'Peony',
  'role': 'heart',
  'description': 'Airy floral sweetness with a fresh smile.',
  'fallback': 0,
  'tags': ['romantic', 'airy', 'soft', 'flower shop', 'fresh', 'floral']},
 {'name': 'Suede',
  'role': 'heart',
  'description': 'Smooth, modern texture with a luxe city feel.',
  'fallback': 0,
  'tags': ['night out', 'modern', 'smooth', 'luxury', 'leather', 'soft']},
 {'name': 'Incense',
  'role': 'base',
  'description': 'Smoldering ritual smoke with a mysterious core.',
  'fallback': 0,
  'tags': ['mystic', 'night', 'smoke', 'ritual', 'dark', 'smoky']},
 {'name': 'Cedarwood',
  'role': 'base',
  'description': 'Dry, architectural wood with clean structure.',
  'fallback': 1,
  'tags': ['woody', 'dry', 'architectural', 'clean', 'outdoors', 'cedar']},
 {'name': 'Sandalwood',
  'role': 'base',
  'description': 'Creamy wood that feels smooth and intimate.',
  'fallback': 1,
  'tags': ['warm', 'creamy', 'smooth', 'romantic', 'base', 'woody']},
 {'name': 'Vetiver',
  'role': 'base',
  'description': 'Dry earth and green roots with a grounded finish.',
  'fallback': 0,
  'tags': ['earthy', 'dry', 'green', 'night', 'grounded', 'woody']},
 {'name': 'Patchouli',
  'role': 'base',
  'description': 'Dark, smoky earthiness with bohemian depth.',
  'fallback': 0,
  'tags': ['dark', 'bohemian', 'smoky', 'night out', 'earthy', 'patchouli']},
 {'name': 'Amber',
  'role': 'base',
  'description': 'Golden warmth that glows into the evening.',
  'fallback': 1,
  'tags': ['warm', 'golden', 'romantic', 'evening', 'glow', 'luxury']},
 {'name': 'Vanilla',
  'role': 'base',
  'description': 'Comforting sweetness with an easy, soft finish.',
  'fallback': 1,
  'tags': ['sweet', 'comforting', 'romantic', 'soft', 'warm', 'gourmand']},
 {'name': 'Tonka Bean',
  'role': 'base',
  'description': 'Smooth gourmand warmth with a cozy pulse.',
  'fallback': 0,
  'tags': ['gourmand', 'warm', 'soft', 'evening', 'smooth', 'sweet']},
 {'name': 'Musk',
  'role': 'base',
  'description': 'Skin-close softness that feels intimate and clean.',
  'fallback': 1,
  'tags': ['skin', 'clean', 'soft', 'intimate', 'romantic', 'muted']},
 {'name': 'Leather',
  'role': 'base',
  'description': 'Urban, bold, and a little smoky around the edges.',
  'fallback': 0,
  'tags': ['dark', 'night out', 'smoke', 'urban', 'bold', 'smoky']},
 {'name': 'Oakmoss',
  'role': 'base',
  'description': 'Classic green earth with a forest shadow.',
  'fallback': 0,
  'tags': ['green', 'earthy', 'forest', 'classic', 'dark', 'mossy']},
 {'name': 'Smoke',
  'role': 'base',
  'description': 'Dry smoke that adds drama and shadow.',
  'fallback': 0,
  'tags': ['smoky', 'dark', 'bonfire', 'night', 'dramatic', 'ritual']},
 {'name': 'Cocoa',
  'role': 'base',
  'description': 'Dark, cozy sweetness with a soft gourmand edge.',
  'fallback': 0,
  'tags': ['gourmand', 'warm', 'dark', 'soft', 'cozy', 'sweet']},
 {'name': 'Benzoin',
  'role': 'base',
  'description': 'Resinous warmth that makes the whole blend glow.',
  'fallback': 0,
  'tags': ['resinous', 'warm', 'glow', 'amber', 'soft', 'luxury']},
 {'name': 'Labdanum',
  'role': 'base',
  'description': 'Dense amber resin with dark, plush depth.',
  'fallback': 0,
  'tags': ['amber', 'resinous', 'dark', 'smoky', 'luxury', 'warm']},
 {'name': 'Sea Salt',
  'role': 'top',
  'description': 'Open-air marine freshness with a breezy lift.',
  'fallback': 0,
  'tags': ['marine', 'fresh', 'beach', 'clean', 'open air', 'ocean']},
 {'name': 'Coconut Water',
  'role': 'top',
  'description': 'Bright, airy, beachy, and easygoing.',
  'fallback': 0,
  'tags': ['beach', 'bright', 'soft', 'summer', 'clean', 'marine']},
 {'name': 'Fig Leaf',
  'role': 'heart',
  'description': 'Green, modern, and softly sunlit.',
  'fallback': 0,
  'tags': ['garden', 'modern', 'green', 'sunlit', 'soft', 'botanical']},
 {'name': 'Cherry Blossom',
  'role': 'heart',
  'description': 'Delicate spring florals with a light romantic haze.',
  'fallback': 0,
  'tags': ['romantic', 'airy', 'spring', 'soft', 'delicate', 'floral']},
 {'name': 'Plum',
  'role': 'heart',
  'description': 'Dark fruit with velvet richness.',
  'fallback': 0,
  'tags': ['dark fruit', 'velvet', 'evening', 'romantic', 'rich', 'fruit']},
 {'name': 'Cashmere Wood',
  'role': 'base',
  'description': 'Soft wood with a smooth, modern luxury feel.',
  'fallback': 0,
  'tags': ['soft', 'luxury', 'warm', 'smooth', 'modern', 'woody']},
 {'name': 'Matcha',
  'role': 'top',
  'description': 'Calm green tea freshness with a minimal mood.',
  'fallback': 0,
  'tags': ['green', 'calm', 'minimal', 'tea', 'clean', 'quiet']},
 {'name': 'Saffron',
  'role': 'heart',
  'description': 'Spicy gold with a rich, glowing effect.',
  'fallback': 0,
  'tags': ['spicy', 'luxury', 'golden', 'warm', 'night out', 'saffron']},
 {'name': 'Basil',
  'role': 'top',
  'description': 'Bright herbal sharpness with clean green lift.',
  'fallback': 0,
  'tags': ['green', 'fresh', 'bright', 'herbal', 'crisp', 'botanical']},
 {'name': 'Clary Sage',
  'role': 'heart',
  'description': 'Herbal calm with a spa-like green softness.',
  'fallback': 0,
  'tags': ['herbal', 'spa', 'calm', 'clean', 'quiet', 'green']},
 {'name': 'Rain Accord',
  'role': 'top',
  'description': 'Transparent rainwater with a cool, reflective hush.',
  'fallback': 0,
  'tags': ['rain', 'sad', 'melancholy', 'cool', 'fresh air', 'quiet']},
 {'name': 'Violet',
  'role': 'heart',
  'description': 'Tender, powdery floral color with a blue emotional cast.',
  'fallback': 0,
  'tags': ['violet', 'sad', 'nostalgic', 'powdery', 'soft', 'floral']},
 {'name': 'Black Tea',
  'role': 'heart',
  'description': 'Dry tea leaves with a composed, introspective mood.',
  'fallback': 0,
  'tags': ['tea', 'melancholy', 'quiet', 'elegant', 'dry', 'nostalgic']},
 {'name': 'Mineral Water',
  'role': 'top',
  'description': 'Cool, stony freshness that feels distant and glassy.',
  'fallback': 0,
  'tags': ['cool', 'lonely', 'minimal', 'water', 'clean', 'muted']},
 {'name': 'Paper',
  'role': 'heart',
  'description': 'Soft paper dust with a private, remembered quality.',
  'fallback': 0,
  'tags': ['paper', 'nostalgic', 'quiet', 'powdery', 'minimal', 'soft', 'artistic']},
 {'name': 'Heliotrope',
  'role': 'heart',
  'description': 'Powdery almond sweetness with a gentle, comforted glow.',
  'fallback': 0,
  'tags': ['comforted', 'powdery', 'soft', 'sweet', 'nostalgic', 'gourmand']},
 {'name': 'Honey',
  'role': 'heart',
  'description': 'Golden sweetness with a warm, hopeful radiance.',
  'fallback': 0,
  'tags': ['hopeful', 'golden', 'warm', 'comforting', 'sunrise', 'sweet']},
 {'name': 'Mandarin',
  'role': 'top',
  'description': 'Juicy orange brightness with an easy happy lift.',
  'fallback': 0,
  'tags': ['happy', 'joyful', 'orange', 'bright', 'citrus', 'sparkling']},
 {'name': 'Yuzu',
  'role': 'top',
  'description': 'Electric citrus sparkle with clean, joyful snap.',
  'fallback': 0,
  'tags': ['joyful', 'euphoric', 'sparkling', 'bright', 'citrus', 'fresh']},
 {'name': 'Champagne Accord',
  'role': 'top',
  'description': 'Effervescent fizz for celebration and kinetic joy.',
  'fallback': 0,
  'tags': ['euphoric', 'sparkling', 'night out', 'luminous', 'happy', 'luxury']},
 {'name': 'Rice Steam',
  'role': 'heart',
  'description': 'Soft, warm steam that feels close and emotionally gentle.',
  'fallback': 0,
  'tags': ['comforted', 'soft', 'warm', 'skin', 'quiet', 'minimal']},
 {'name': 'Milk Accord',
  'role': 'heart',
  'description': 'Creamy softness with a protected, soothing mood.',
  'fallback': 0,
  'tags': ['comforted', 'creamy', 'soft', 'gourmand', 'warm', 'vulnerable']},
 {'name': 'Burnt Sugar',
  'role': 'base',
  'description': 'Dark caramel sweetness with a scorched emotional edge.',
  'fallback': 0,
  'tags': ['angry', 'gourmand', 'smoky', 'dark', 'sweet', 'dramatic']},
 {'name': 'Gunmetal',
  'role': 'base',
  'description': 'Cold metal and shadow for tense, restless moods.',
  'fallback': 0,
  'tags': ['anxious', 'restless', 'metallic', 'cold', 'industrial', 'dark']},
 {'name': 'Black Pepper',
  'role': 'top',
  'description': 'Dry heat and sharp movement with a confrontational spark.',
  'fallback': 0,
  'tags': ['angry', 'peppery', 'bold', 'spicy', 'restless', 'dry']},
 {'name': 'Tuberose',
  'role': 'heart',
  'description': 'Creamy white floral intensity with sensual confidence.',
  'fallback': 0,
  'tags': ['sensual', 'confident', 'floral', 'creamy', 'night out', 'luminous']},
 {'name': 'Osmanthus',
  'role': 'heart',
  'description': 'Apricot floral suede with elegant, bittersweet warmth.',
  'fallback': 0,
  'tags': ['bittersweet', 'romantic', 'suede', 'soft', 'fruit', 'elegant']},
 {'name': 'Myrrh',
  'role': 'base',
  'description': 'Quiet resin smoke with a solemn, mysterious depth.',
  'fallback': 0,
  'tags': ['grief', 'mysterious', 'incense', 'resinous', 'dark', 'ritual']},
 {'name': 'Petrichor',
  'role': 'top',
  'description': 'Wet stone and soil after rain, earthy and emotionally clean.',
  'fallback': 0,
  'tags': ['rain', 'melancholy', 'earthy', 'fresh air', 'grounded', 'hopeful']},
 {'name': 'White Amber',
  'role': 'base',
  'description': 'Soft amber glow with clean skin warmth.',
  'fallback': 0,
  'tags': ['hopeful', 'skin', 'soft', 'amber', 'clean', 'luminous']},
 {'name': 'Cloud Musk',
  'role': 'base',
  'description': 'Airy musk with a dreamlike, barely-there tenderness.',
  'fallback': 0,
  'tags': ['dreamy', 'vulnerable', 'soft', 'skin', 'airy', 'musk']},
 {'name': 'Absinthe',
  'role': 'top',
  'description': 'Bitter green electricity with a strange restless shimmer.',
  'fallback': 0,
  'tags': ['restless', 'mysterious', 'green', 'bitter', 'electric', 'night']},
 {'name': 'Desert Air',
  'role': 'top',
  'description': 'Dry mineral air with sunlit heat and wide-open space.',
  'fallback': 0,
  'tags': ['desert', 'arid', 'sand', 'sunbaked', 'dry heat', 'mineral']},
 {'name': 'Cactus Flower',
  'role': 'heart',
  'description': 'Watery desert bloom with a soft green floral lift.',
  'fallback': 0,
  'tags': ['desert', 'cactus', 'green', 'floral', 'water', 'sunlit']},
 {'name': 'Sagebrush',
  'role': 'heart',
  'description': 'Dusty herbal green with dry, sun-warmed edges.',
  'fallback': 0,
  'tags': ['desert', 'sage', 'chaparral', 'herbal', 'dry', 'earthy']},
 {'name': 'Hot Sand',
  'role': 'base',
  'description': 'Warm sand and dry amber heat radiating off the ground.',
  'fallback': 0,
  'tags': ['sand', 'sunbaked', 'dry heat', 'warm', 'amber', 'dunes']},
 {'name': 'Juniper',
  'role': 'heart',
  'description': 'Crisp evergreen brightness with a cool mountain snap.',
  'fallback': 0,
  'tags': ['juniper', 'mountain', 'forest', 'fresh air', 'green', 'cold']},
 {'name': 'Pine Needles',
  'role': 'top',
  'description': 'Sharp forest freshness with resin and winter air.',
  'fallback': 0,
  'tags': ['pine', 'forest', 'winter', 'cold', 'fresh air', 'green']},
 {'name': 'Snow Accord',
  'role': 'top',
  'description': 'Clean frozen air with a soft white hush.',
  'fallback': 0,
  'tags': ['snow', 'frost', 'winter', 'cold', 'clean', 'quiet']},
 {'name': 'Apple Skin',
  'role': 'top',
  'description': 'Crisp orchard fruit with a bright autumn snap.',
  'fallback': 0,
  'tags': ['apple', 'autumn', 'fall', 'harvest', 'crisp', 'fresh']},
 {'name': 'Hay',
  'role': 'heart',
  'description': 'Dry golden grass with late-summer warmth.',
  'fallback': 0,
  'tags': ['hay', 'summer', 'autumn', 'harvest', 'dry', 'golden']},
 {'name': 'Wet Soil',
  'role': 'base',
  'description': 'Dark damp earth after rain, green and grounded.',
  'fallback': 0,
  'tags': ['soil', 'rain', 'forest', 'earthy', 'green', 'petrichor']},
 {'name': 'Red Berries',
  'role': 'top',
  'description': 'Tart red fruit with a bright, romantic pulse.',
  'fallback': 0,
  'tags': ['red', 'fruit', 'romantic', 'bright', 'flirty', 'bold']},
 {'name': 'Blackcurrant',
  'role': 'heart',
  'description': 'Dark berry richness with green shadow and velvet depth.',
  'fallback': 0,
  'tags': ['black', 'purple', 'dark fruit', 'green', 'velvet', 'rich']},
 {'name': 'White Tea',
  'role': 'heart',
  'description': 'Clean pale tea with a sheer, polished calm.',
  'fallback': 0,
  'tags': ['white', 'tea', 'clean', 'minimal', 'calm', 'soft']},
 {'name': 'Blue Lotus',
  'role': 'heart',
  'description': 'Cool watery floral with a blue, dreamlike hush.',
  'fallback': 0,
  'tags': ['blue', 'water', 'dreamy', 'cool', 'floral', 'soft']},
 {'name': 'Concrete',
  'role': 'base',
  'description': 'Grey mineral texture with a rain-washed urban feel.',
  'fallback': 0,
  'tags': ['grey', 'gray', 'concrete', 'mineral', 'rain', 'urban']},
 {'name': 'Electric Citrus',
  'role': 'top',
  'description': 'Neon-bright citrus with a glossy, futuristic charge.',
  'fallback': 0,
  'tags': ['neon', 'electric', 'citrus', 'futuristic', 'bright', 'glossy']}]
