"""Seed note definitions for the local scent catalog."""

from __future__ import annotations


NOTE_SEEDS = [{'name': 'Aldehydes',
  'role': 'top',
  'description': 'sparkling and polished,\nlifted by a quiet metallic breath.',
  'fallback': 1,
  'tags': ['robotic', 'futuristic', 'clean', 'bright', 'sunrise', 'silver', 'polished', 'cold metal', 'reflective']},
 {'name': 'Metallic Accord',
  'role': 'top',
  'description': 'an industrial, chrome-like shimmer with a city edge',
  'fallback': 0,
  'tags': ['robotic', 'metallic', 'industrial', 'city lights', 'futuristic', 'glossy', 'cold metal', 'reflective']},
 {'name': 'Ozone',
  'role': 'top',
  'description': 'crisp ozonic air with cool minerals and a wet-stone edge',
  'fallback': 1,
  'tags': ['fresh air', 'electric', 'rain', 'night drive', 'skyline', 'clean', 'wet air', 'wet stone', 'clean skin']},
 {'name': 'Bergamot',
  'role': 'top',
  'description': 'bright citrus with a crisp, lifted opening',
  'fallback': 1,
  'tags': ['sunrise', 'bright', 'citrus', 'city lights', 'energetic', 'sparkling', 'clean', 'citrus peel', 'zest']},
 {'name': 'Grapefruit Zest',
  'role': 'top',
  'description': 'sharp, juicy citrus with a playful edge',
  'fallback': 0,
  'tags': ['bright', 'citrus', 'sporty', 'sunrise', 'fresh', 'uplifting', 'citrus peel', 'zest']},
 {'name': 'Lemon Peel',
  'role': 'top',
  'description': 'bright lemon peel with tart juice and clean citrus zest',
  'fallback': 0,
  'tags': ['bright', 'sparkling', 'clean', 'daylight', 'uplifting', 'citrus', 'citrus peel', 'zest', 'clean skin']},
 {'name': 'Pink Pepper',
  'role': 'top',
  'description': 'flirty sparkle with a modern peppery bite',
  'fallback': 0,
  'tags': ['romantic', 'modern', 'sparkling', 'night out', 'flirty', 'peppery', 'dry spice', 'aromatic']},
 {'name': 'Cardamom',
  'role': 'heart',
  'description': 'warm cardamom spice with a soft woody sweetness',
  'fallback': 1,
  'tags': ['spicy', 'warm spice', 'night out', 'sophisticated', 'bold', 'smooth', 'dry spice', 'aromatic']},
 {'name': 'Ginger',
  'role': 'top',
  'description': 'fresh ginger root with a bright peppery bite',
  'fallback': 0,
  'tags': ['spicy', 'zesty', 'energetic', 'modern', 'bold', 'daylight', 'dry spice', 'aromatic']},
 {'name': 'Green Tea',
  'role': 'heart',
  'description': 'soft, minimalist freshness with a quiet calm',
  'fallback': 1,
  'tags': ['calm', 'minimal', 'quiet', 'clean', 'soft', 'tea', 'green', 'green stems', 'crushed leaves']},
 {'name': 'Mint',
  'role': 'top',
  'description': 'cool mint leaves with a crisp green freshness',
  'fallback': 0,
  'tags': ['cool', 'fresh', 'clean', 'morning', 'crisp', 'green', 'green stems', 'crushed leaves', 'clean skin']},
 {'name': 'Eucalyptus',
  'role': 'top',
  'description': 'spa-like freshness that clears the room',
  'fallback': 0,
  'tags': ['spa', 'fresh air', 'calm', 'clean', 'minimal', 'fresh', 'clean skin', 'soft fabric']},
 {'name': 'Neroli',
  'role': 'heart',
  'description': 'sunlit citrus blossom with a tailored finish',
  'fallback': 1,
  'tags': ['sunlit', 'white shirt', 'clean', 'romantic', 'bright', 'citrus', 'floral', 'citrus peel', 'zest']},
 {'name': 'Pear Skin',
  'role': 'top',
  'description': 'fresh pear skin with a watery sweetness and soft musk',
  'fallback': 0,
  'tags': ['soft', 'modern', 'airy', 'romantic', 'fresh', 'bright', 'fruit skin', 'watery fruit']},
 {'name': 'Violet Leaf',
  'role': 'heart',
  'description': 'cool green leaves with a damp violet-like freshness',
  'fallback': 0,
  'tags': ['rain', 'cool', 'green', 'muted', 'fresh', 'botanical', 'wet air', 'wet stone', 'green stems']},
 {'name': 'Rose',
  'role': 'heart',
  'description': 'classic romantic bloom with velvet softness',
  'fallback': 1,
  'tags': ['romantic', 'night out', 'soft', 'velvet', 'date night', 'floral', 'petals', 'flower shop']},
 {'name': 'Jasmine',
  'role': 'heart',
  'description': 'creamy jasmine petals with a warm indolic sweetness',
  'fallback': 1,
  'tags': ['romantic', 'glowing', 'night out', 'soft', 'floral', 'luminous', 'petals', 'flower shop']},
 {'name': 'Orange Blossom',
  'role': 'heart',
  'description': 'fresh orange blossom with soft honeyed petals',
  'fallback': 0,
  'tags': ['romantic', 'sunlit', 'soft', 'clean', 'date night', 'floral', 'petals', 'flower shop', 'clean skin']},
 {'name': 'Iris',
  'role': 'heart',
  'description': 'powdery iris root with dry violet and soft suede',
  'fallback': 0,
  'tags': ['powdery', 'elegant', 'artistic', 'romantic', 'cool', 'floral', 'petals', 'flower shop']},
 {'name': 'Lavender',
  'role': 'heart',
  'description': 'herbal lavender with clean camphor and soft florals',
  'fallback': 1,
  'tags': ['calm', 'night', 'clean', 'quiet', 'soft', 'floral', 'herbal', 'green stems', 'crushed leaves']},
 {'name': 'Peony',
  'role': 'heart',
  'description': 'airy floral sweetness with a fresh smile',
  'fallback': 0,
  'tags': ['romantic', 'airy', 'soft', 'flower shop', 'fresh', 'floral', 'petals']},
 {'name': 'Suede',
  'role': 'heart',
  'description': 'soft suede with dry leather and a smooth musky finish',
  'fallback': 0,
  'tags': ['night out', 'modern', 'smooth', 'luxury', 'leather', 'soft', 'smoldering', 'charred']},
 {'name': 'Incense',
  'role': 'base',
  'description': 'smoldering ritual smoke with a mysterious core',
  'fallback': 0,
  'tags': ['mystic', 'night', 'smoke', 'ritual', 'dark', 'smoky', 'smoldering', 'charred']},
 {'name': 'Cedarwood',
  'role': 'base',
  'description': 'dry, architectural wood with clean structure',
  'fallback': 1,
  'tags': ['woody', 'dry', 'architectural', 'clean', 'outdoors', 'cedar', 'dry wood', 'tree bark', 'clean skin']},
 {'name': 'Sandalwood',
  'role': 'base',
  'description': 'creamy sandalwood with soft milky wood and warm spice',
  'fallback': 1,
  'tags': ['warm', 'creamy', 'smooth', 'romantic', 'base', 'woody', 'dry wood', 'tree bark']},
 {'name': 'Vetiver',
  'role': 'base',
  'description': 'dry earth and green roots with a grounded finish',
  'fallback': 0,
  'tags': ['earthy', 'dry', 'green', 'night', 'grounded', 'woody', 'green stems', 'crushed leaves', 'dry wood']},
 {'name': 'Patchouli',
  'role': 'base',
  'description': 'dark, smoky earthiness with bohemian depth',
  'fallback': 0,
  'tags': ['dark', 'bohemian', 'smoky', 'night out', 'earthy', 'patchouli', 'dirty', 'smoldering', 'charred']},
 {'name': 'Amber',
  'role': 'base',
  'description': 'sweet amber resin with a warm balsamic finish',
  'fallback': 1,
  'tags': ['warm', 'golden', 'romantic', 'evening', 'glow', 'luxury', 'amber resin', 'balsamic']},
 {'name': 'Vanilla',
  'role': 'base',
  'description': 'comforting sweetness with an easy, soft finish',
  'fallback': 1,
  'tags': ['sweet', 'comforting', 'romantic', 'soft', 'warm', 'gourmand', 'edible', 'sugar']},
 {'name': 'Tonka Bean',
  'role': 'base',
  'description': 'smooth gourmand warmth with a cozy pulse',
  'fallback': 0,
  'tags': ['gourmand', 'warm', 'soft', 'evening', 'smooth', 'sweet', 'edible', 'sugar']},
 {'name': 'Musk',
  'role': 'base',
  'description': 'clean skin musk with a soft powdery finish',
  'fallback': 1,
  'tags': ['skin', 'clean', 'soft', 'intimate', 'romantic', 'muted', 'clean skin', 'soft fabric']},
 {'name': 'Leather',
  'role': 'base',
  'description': 'urban, bold, and a little smoky around the edges',
  'fallback': 0,
  'tags': ['dark', 'night out', 'smoke', 'urban', 'bold', 'smoky', 'dirty', 'smoldering', 'charred']},
 {'name': 'Oakmoss',
  'role': 'base',
  'description': 'classic green earth with a forest shadow',
  'fallback': 0,
  'tags': ['green', 'earthy', 'forest', 'classic', 'dark', 'mossy', 'green stems', 'crushed leaves', 'mineral']},
 {'name': 'Smoke',
  'role': 'base',
  'description': 'dry wood smoke with a charred, ashy edge',
  'fallback': 0,
  'tags': ['smoky', 'dark', 'bonfire', 'night', 'dramatic', 'ritual', 'dirty', 'smoldering', 'charred']},
 {'name': 'Cocoa',
  'role': 'base',
  'description': 'dark, cozy sweetness with a soft gourmand edge',
  'fallback': 0,
  'tags': ['gourmand', 'warm', 'dark', 'soft', 'cozy', 'sweet', 'edible', 'sugar']},
 {'name': 'Benzoin',
  'role': 'base',
  'description': 'sweet balsamic resin with vanilla-like warmth',
  'fallback': 0,
  'tags': ['resinous', 'warm', 'glow', 'amber', 'soft', 'luxury', 'balsamic resin', 'vanilla resin']},
 {'name': 'Labdanum',
  'role': 'base',
  'description': 'dense amber resin with dark, plush depth',
  'fallback': 0,
  'tags': ['amber', 'resinous', 'dark', 'smoky', 'luxury', 'warm', 'smoldering', 'charred']},
 {'name': 'Sea Salt',
  'role': 'top',
  'description': 'open-air marine freshness with a breezy lift',
  'fallback': 0,
  'tags': ['marine', 'fresh', 'beach', 'clean', 'open air', 'ocean', 'wet air', 'wet stone', 'clean skin']},
 {'name': 'Coconut',
  'role': 'top',
  'description': 'creamy coconut flesh with a soft solar sweetness',
  'fallback': 0,
  'tags': ['beach', 'bright', 'soft', 'summer', 'clean', 'marine', 'wet air', 'wet stone', 'clean skin']},
 {'name': 'Fig Leaf',
  'role': 'heart',
  'description': 'green, modern, and softly sunlit',
  'fallback': 0,
  'tags': ['garden', 'modern', 'green', 'sunlit', 'soft', 'botanical', 'green stems', 'crushed leaves']},
 {'name': 'Cherry Blossom',
  'role': 'heart',
  'description': 'delicate spring florals with a light romantic haze',
  'fallback': 0,
  'tags': ['romantic', 'airy', 'spring', 'soft', 'delicate', 'floral', 'petals', 'flower shop']},
 {'name': 'Plum',
  'role': 'heart',
  'description': 'dark fruit with velvet richness',
  'fallback': 0,
  'tags': ['dark fruit', 'velvet', 'evening', 'romantic', 'rich', 'fruit', 'fruit skin', 'juicy']},
 {'name': 'Cashmere Wood',
  'role': 'base',
  'description': 'soft wood with a smooth, modern luxury feel',
  'fallback': 0,
  'tags': ['soft', 'luxury', 'warm', 'smooth', 'modern', 'woody', 'dry wood', 'tree bark']},
 {'name': 'Matcha',
  'role': 'top',
  'description': 'green tea powder with grassy, slightly bitter freshness',
  'fallback': 0,
  'tags': ['green', 'calm', 'minimal', 'tea', 'clean', 'quiet', 'green stems', 'crushed leaves', 'clean skin']},
 {'name': 'Saffron',
  'role': 'heart',
  'description': 'dry saffron threads with warm leathery spice',
  'fallback': 0,
  'tags': ['spicy', 'luxury', 'golden', 'warm', 'night out', 'saffron', 'dry spice', 'aromatic']},
 {'name': 'Basil',
  'role': 'top',
  'description': 'bright herbal sharpness with clean green lift',
  'fallback': 0,
  'tags': ['green', 'fresh', 'bright', 'herbal', 'crisp', 'botanical', 'green stems', 'crushed leaves']},
 {'name': 'Clary Sage',
  'role': 'heart',
  'description': 'herbal calm with a spa-like green softness',
  'fallback': 0,
  'tags': ['herbal', 'spa', 'calm', 'clean', 'quiet', 'green', 'green stems', 'crushed leaves', 'clean skin']},
 {'name': 'Rain Accord',
  'role': 'top',
  'description': 'cool rainwater with wet stone and clean ozone',
  'fallback': 0,
  'tags': ['rain', 'sad', 'melancholy', 'cool', 'fresh air', 'quiet', 'wet air', 'wet stone']},
 {'name': 'Violet',
  'role': 'heart',
  'description': 'powdery violet petals with a soft green sweetness',
  'fallback': 0,
  'tags': ['violet', 'sad', 'nostalgic', 'powdery', 'soft', 'floral', 'petals', 'flower shop']},
 {'name': 'Black Tea',
  'role': 'heart',
  'description': 'dry black tea leaves with tannic, slightly smoky warmth',
  'fallback': 0,
  'tags': ['tea', 'melancholy', 'quiet', 'elegant', 'dry', 'nostalgic', 'tea leaves', 'tannic']},
 {'name': 'Mineral Water',
  'role': 'top',
  'description': 'cool mineral water with a clean stony freshness',
  'fallback': 0,
  'tags': ['cool', 'lonely', 'minimal', 'water', 'clean', 'muted', 'wet air', 'wet stone', 'clean skin']},
 {'name': 'Paper',
  'role': 'heart',
  'description': 'dry paper fibers with soft dust and pale wood',
  'fallback': 0,
  'tags': ['paper', 'nostalgic', 'quiet', 'powdery', 'minimal', 'soft', 'artistic', 'paper fiber', 'dry paper']},
 {'name': 'Heliotrope',
  'role': 'heart',
  'description': 'powdery heliotrope with almond and vanilla sweetness',
  'fallback': 0,
  'tags': ['comforted', 'powdery', 'soft', 'sweet', 'nostalgic', 'gourmand', 'edible', 'sugar']},
 {'name': 'Honey',
  'role': 'heart',
  'description': 'golden honey with waxy sweetness and warm florals',
  'fallback': 0,
  'tags': ['hopeful', 'golden', 'warm', 'comforting', 'sunrise', 'sweet', 'edible', 'sugar']},
 {'name': 'Mandarin',
  'role': 'top',
  'description': 'juicy mandarin peel with sweet orange pulp',
  'fallback': 0,
  'tags': ['happy', 'joyful', 'orange', 'bright', 'citrus', 'sparkling', 'citrus peel', 'zest']},
 {'name': 'Yuzu',
  'role': 'top',
  'description': 'sharp yuzu peel with tart grapefruit and green citrus',
  'fallback': 0,
  'tags': ['joyful', 'euphoric', 'sparkling', 'bright', 'citrus', 'fresh', 'citrus peel', 'zest']},
 {'name': 'Champagne Accord',
  'role': 'top',
  'description': 'dry sparkling wine with crisp citrus and soft yeast',
  'fallback': 0,
  'tags': ['euphoric', 'sparkling', 'night out', 'luminous', 'happy', 'luxury', 'sparkling wine', 'effervescence']},
 {'name': 'Rice Steam',
  'role': 'heart',
  'description': 'warm rice steam with a soft starchy sweetness',
  'fallback': 0,
  'tags': ['comforted', 'soft', 'warm', 'skin', 'quiet', 'minimal', 'clean skin', 'soft fabric']},
 {'name': 'Milk Accord',
  'role': 'heart',
  'description': 'creamy milk with soft vanilla and clean musk',
  'fallback': 0,
  'tags': ['comforted', 'creamy', 'soft', 'gourmand', 'warm', 'vulnerable', 'edible', 'sugar']},
 {'name': 'Burnt Sugar',
  'role': 'base',
  'description': 'dark caramelized sugar with a smoky bitter edge',
  'fallback': 0,
  'tags': ['angry', 'gourmand', 'smoky', 'dark', 'sweet', 'dramatic', 'smoldering', 'charred', 'edible']},
 {'name': 'Gunmetal',
  'role': 'base',
  'description': 'cold metal with a dry mineral and inky edge',
  'fallback': 0,
  'tags': ['anxious', 'restless', 'metallic', 'cold', 'industrial', 'dark', 'cold metal', 'reflective']},
 {'name': 'Black Pepper',
  'role': 'top',
  'description': 'dry black pepper with sharp heat and woody spice',
  'fallback': 0,
  'tags': ['angry', 'peppery', 'bold', 'spicy', 'restless', 'dry', 'dry spice', 'aromatic']},
 {'name': 'Tuberose',
  'role': 'heart',
  'description': 'creamy tuberose with sweet white petals and green stems',
  'fallback': 0,
  'tags': ['sensual', 'confident', 'floral', 'creamy', 'night out', 'luminous', 'petals', 'flower shop']},
 {'name': 'Osmanthus',
  'role': 'heart',
  'description': 'apricot-like osmanthus with soft suede and tea notes',
  'fallback': 0,
  'tags': ['bittersweet', 'romantic', 'suede', 'soft', 'fruit', 'elegant', 'fruit skin', 'juicy']},
 {'name': 'Myrrh',
  'role': 'base',
  'description': 'dark myrrh resin with incense smoke and balsamic warmth',
  'fallback': 0,
  'tags': ['grief', 'mysterious', 'incense', 'resinous', 'dark', 'ritual', 'smoldering', 'charred']},
 {'name': 'Petrichor',
  'role': 'top',
  'description': 'wet stone and soil after rain with a clean mineral edge',
  'fallback': 0,
  'tags': ['rain', 'melancholy', 'earthy', 'fresh air', 'grounded', 'hopeful', 'wet air', 'wet stone', 'mineral']},
 {'name': 'White Amber',
  'role': 'base',
  'description': 'soft amber resin with clean musk and warm skin notes',
  'fallback': 0,
  'tags': ['hopeful', 'skin', 'soft', 'amber', 'clean', 'luminous', 'clean skin', 'soft fabric']},
 {'name': 'Absinthe',
  'role': 'top',
  'description': 'bitter green herbs with anise, wormwood, and sharp sweetness',
  'fallback': 0,
  'tags': ['restless', 'mysterious', 'green', 'bitter', 'electric', 'night', 'green stems', 'crushed leaves']},
 {'name': 'Desert Air',
  'role': 'top',
  'description': 'dry mineral air with sunlit heat and wide-open space',
  'fallback': 0,
  'tags': ['desert', 'arid', 'sand', 'sunbaked', 'dry heat', 'mineral', 'grounded']},
 {'name': 'Cactus Flower',
  'role': 'heart',
  'description': 'watery desert bloom with a soft green floral lift',
  'fallback': 0,
  'tags': ['desert', 'cactus', 'green', 'floral', 'water', 'sunlit', 'wet air', 'wet stone', 'green stems']},
 {'name': 'Sagebrush',
  'role': 'heart',
  'description': 'dusty herbal green with dry, sun-warmed edges',
  'fallback': 0,
  'tags': ['desert', 'sage', 'chaparral', 'herbal', 'dry', 'earthy', 'green stems', 'crushed leaves', 'mineral']},
 {'name': 'Hot Sand',
  'role': 'base',
  'description': 'warm sand and dry amber heat radiating off the ground',
  'fallback': 0,
  'tags': ['sand', 'sunbaked', 'dry heat', 'warm', 'amber', 'dunes', 'mineral', 'grounded']},
 {'name': 'Juniper',
  'role': 'heart',
  'description': 'crisp evergreen brightness with a cool mountain snap',
  'fallback': 0,
  'tags': ['juniper', 'mountain', 'forest', 'fresh air', 'green', 'cold', 'green stems', 'crushed leaves']},
 {'name': 'Pine Needles',
  'role': 'top',
  'description': 'sharp forest freshness with resin and winter air',
  'fallback': 0,
  'tags': ['pine', 'forest', 'winter', 'cold', 'fresh air', 'green', 'green stems', 'crushed leaves', 'dry wood']},
 {'name': 'Snow Accord',
  'role': 'top',
  'description': 'cold clean air with frost, pine, and soft musk',
  'fallback': 0,
  'tags': ['snow', 'frost', 'winter', 'cold', 'clean', 'quiet', 'clean skin', 'soft fabric']},
 {'name': 'Apple Skin',
  'role': 'top',
  'description': 'crisp orchard fruit with a bright autumn snap',
  'fallback': 0,
  'tags': ['apple', 'autumn', 'fall', 'harvest', 'crisp', 'fresh', 'fruit skin', 'juicy']},
 {'name': 'Hay',
  'role': 'heart',
  'description': 'dry golden grass with late-summer warmth',
  'fallback': 0,
  'tags': ['hay', 'summer', 'autumn', 'harvest', 'dry', 'golden', 'dry grass', 'sun-dried']},
 {'name': 'Wet Soil',
  'role': 'base',
  'description': 'dark damp earth after rain, green and grounded',
  'fallback': 0,
  'tags': ['soil', 'rain', 'forest', 'earthy', 'green', 'petrichor', 'dirty', 'wet air', 'wet stone']},
 {'name': 'Red Berries',
  'role': 'top',
  'description': 'tart red fruit with a bright, romantic pulse',
  'fallback': 0,
  'tags': ['red', 'fruit', 'romantic', 'bright', 'flirty', 'bold', 'fruit skin', 'juicy']},
 {'name': 'Blackcurrant',
  'role': 'heart',
  'description': 'dark berry richness with green shadow and velvet depth',
  'fallback': 0,
  'tags': ['black', 'purple', 'dark fruit', 'green', 'velvet', 'rich', 'green stems', 'crushed leaves']},
 {'name': 'White Tea',
  'role': 'heart',
  'description': 'clean pale tea with a sheer, polished calm',
  'fallback': 0,
  'tags': ['white', 'tea', 'clean', 'minimal', 'calm', 'soft', 'clean skin', 'soft fabric']},
 {'name': 'Blue Lotus',
  'role': 'heart',
  'description': 'cool watery petals with green stems and soft florals',
  'fallback': 0,
  'tags': ['blue', 'water', 'dreamy', 'cool', 'floral', 'soft', 'wet air', 'wet stone', 'petals']},
 {'name': 'Concrete',
  'role': 'base',
  'description': 'cool grey mineral with damp concrete and rainwater',
  'fallback': 0,
  'tags': ['grey', 'gray', 'concrete', 'mineral', 'rain', 'urban', 'brutalist', 'industrial', 'raw', 'architecture']},
 {'name': 'Electric Citrus',
  'role': 'top',
  'description': 'neon-bright citrus with a glossy, futuristic charge',
  'fallback': 0,
  'tags': ['neon', 'electric', 'citrus', 'futuristic', 'bright', 'glossy', 'cold metal', 'reflective', 'citrus peel']},
 {'name': 'Chrome',
  'role': 'top',
  'description': 'polished metallic shine with a sleek reflective edge',
  'fallback': 0,
  'tags': ['metallic', 'futuristic', 'industrial', 'silver', 'glossy', 'city lights', 'editorial', 'cold metal', 'reflective']},
 {'name': 'Fog',
  'role': 'top',
  'description': 'cool mist with damp air, soft musk, and pale woods',
  'fallback': 0,
  'tags': ['foggy', 'liminal', 'airy', 'quiet', 'muted', 'dreamy', 'rain', 'wet air', 'wet stone']},
 {'name': 'Linen',
  'role': 'heart',
  'description': 'clean woven fabric with airy, coastal simplicity',
  'fallback': 0,
  'tags': ['linen', 'clean', 'white shirt', 'coastal grandmother', 'airy', 'soft', 'minimal', 'fresh', 'clean skin']},
 {'name': 'Velvet',
  'role': 'heart',
  'description': 'plush fabric warmth with a rich, romantic softness',
  'fallback': 0,
  'tags': ['velvet', 'dark feminine', 'romantic', 'night out', 'plush', 'luxury', 'soft', 'plush fabric', 'soft suede']},
 {'name': 'Wildflower',
  'role': 'heart',
  'description': 'fresh meadow flowers with green stems and soft pollen',
  'fallback': 0,
  'tags': ['wildflower', 'fairycore', 'floral', 'green', 'spring', 'dreamy', 'green stems', 'crushed leaves', 'petals']},
 {'name': 'Marble',
  'role': 'base',
  'description': 'cool polished stone with a dry mineral finish',
  'fallback': 0,
  'tags': ['marble', 'cold', 'mineral', 'polished', 'luxury', 'minimal', 'grounded']},
 {'name': 'Ink',
  'role': 'heart',
  'description': 'dark blue-black ink with paper, resin, and a dry edge',
  'fallback': 0,
  'tags': ['ink', 'dark academia', 'paper', 'black', 'blue', 'artistic', 'blue-black ink', 'ink stain']},
 {'name': 'Asphalt Rain',
  'role': 'base',
  'description': 'wet pavement with rainwater, asphalt, and dry smoke',
  'fallback': 0,
  'tags': ['asphalt', 'rain', 'gray', 'urban', 'smoky', 'noir', 'wet air', 'wet stone', 'smoldering']},
 {'name': 'Lipstick',
  'role': 'heart',
  'description': 'powdery rose wax with violet, iris, and soft musk',
  'fallback': 0,
  'tags': ['lipstick', 'powdery', 'rose', 'red', 'coquette', 'romantic', 'petals', 'flower shop']},
 {'name': 'Old Books',
  'role': 'heart',
  'description': 'aged paper, dry wood, and soft academic dust',
  'fallback': 0,
  'tags': ['old books', 'paper', 'library', 'dark academia', 'dusty', 'cedar', 'dry wood', 'tree bark']},
 {'name': 'Black Coffee',
  'role': 'heart',
  'description': 'bitter roasted darkness with focused morning heat',
  'fallback': 0,
  'tags': ['coffee', 'bitter', 'focused', 'dark', 'morning', 'warm', 'roasted coffee', 'coffee beans']},
 {'name': 'Flannel',
  'role': 'heart',
  'description': 'soft worn fabric with cedar, musk, and grunge warmth',
  'fallback': 0,
  'tags': ['flannel', 'grunge', 'soft', 'cedar', 'musk', 'warm', 'dry wood', 'tree bark', 'clean skin']},
 {'name': 'Birthday Cake',
  'role': 'heart',
  'description': 'sweet frosting, vanilla, and the sugar rush of a birthday table',
  'fallback': 0,
  'tags': ['birthday', 'birthday cake', 'cake', 'vanilla', 'sweet', 'celebration', 'happy', 'gourmand', 'dessert', 'sugar', 'party', 'frosting', 'sprinkles']},
 {'name': 'Bouquet',
  'role': 'heart',
  'description': 'fresh-cut blossoms with a celebratory floral lift',
  'fallback': 0,
  'tags': ['bouquet', 'wedding', 'rose', 'peony', 'floral', 'fresh', 'airy', 'white floral', 'flower shop', 'petals', 'spring']},
 {'name': 'Satin',
  'role': 'heart',
  'description': 'smooth polished fabric with a dressed-up romantic sheen',
  'fallback': 0,
  'tags': ['satin', 'wedding', 'romantic', 'smooth', 'luxury', 'polished', 'skin', 'sheen', 'silky', 'elegant', 'soft focus']},
 {'name': 'Ambroxan',
  'role': 'base',
  'description': 'dry amberwood with clean musk and a mineral edge',
  'fallback': 0,
  'tags': ['ambroxan', 'amber', 'modern', 'skin', 'mineral', 'woody', 'clean', 'radiant', 'amberwood', 'diffusive', 'molecule']},
 {'name': 'Iso E Super',
  'role': 'heart',
  'description': 'sheer cedarwood with soft musk and dry amber',
  'fallback': 0,
  'tags': ['iso e super', 'woody', 'airy', 'cedar', 'transparent', 'modern', 'skin', 'smooth', 'cedarwood', 'diffusive', 'woody amber']},
 {'name': 'Cashmeran',
  'role': 'base',
  'description': 'velvety woody musk with spice and warmth',
  'fallback': 0,
  'tags': ['cashmeran', 'woody', 'musky', 'amber', 'spicy', 'warm', 'soft', 'velvet', 'cashmere', 'musky wood', 'modern']},
 {'name': 'Hedione',
  'role': 'heart',
  'description': 'airy jasmine radiance with a fresh luminous lift',
  'fallback': 0,
  'tags': ['hedione', 'jasmine', 'airy', 'radiant', 'fresh', 'floral', 'luminous', 'transparent', 'diffusive', 'jasmine air', 'modern floral']},
 {'name': 'Galaxolide',
  'role': 'base',
  'description': 'clean laundry musk with soft modern smoothness',
  'fallback': 0,
  'tags': ['galaxolide', 'musk', 'clean', 'laundry', 'soft', 'skin', 'modern', 'powdery', 'white musk', 'fresh laundry', 'clean musk']},
 {'name': 'Calone',
  'role': 'top',
  'description': 'marine aquatic freshness with a salty sea breeze',
  'fallback': 0,
  'tags': ['calone', 'marine', 'aquatic', 'sea spray', 'fresh', 'airy', 'ozone', 'water', 'watermelon', 'ocean', 'sea breeze']},
 {'name': 'Orris Butter',
  'role': 'heart',
  'description': 'powdery iris root with lipstick wax and soft suede',
  'fallback': 0,
  'tags': ['orris', 'iris', 'powdery', 'suede', 'lipstick', 'cosmetic', 'elegant', 'pale', 'violet root', 'iris butter', 'powder']},
 {'name': 'Oud',
  'role': 'base',
  'description': 'dark oud wood with leather, resin, and dry smoke',
  'fallback': 0,
  'tags': ['oud', 'woody', 'smoky', 'resinous', 'leather', 'dark', 'luxury', 'rich', 'agarwood', 'oriental', 'dramatic']},
 {'name': 'Ylang Ylang',
  'role': 'heart',
  'description': 'creamy ylang ylang with banana-like petals and soft spice',
  'fallback': 0,
  'tags': ['ylang ylang', 'creamy', 'floral', 'tropical', 'sunny', 'sensual', 'lush', 'sweet', 'solar', 'exotic', 'white floral']},
 {'name': 'Magnolia',
  'role': 'heart',
  'description': 'polished floral with citrus brightness and creamy air',
  'fallback': 0,
  'tags': ['magnolia', 'floral', 'citrus', 'clean', 'creamy', 'airy', 'polished', 'white floral', 'petal', 'sunlit', 'fresh']},
 {'name': 'Mimosa',
  'role': 'heart',
  'description': 'soft yellow floral powder with sunny brightness',
  'fallback': 0,
  'tags': ['mimosa', 'powdery', 'yellow', 'floral', 'soft', 'sunny', 'airy', 'delicate', 'pollen', 'spring', 'sunlit']},
  {'name': 'Lychee',
   'role': 'top',
   'description': 'sweet pink fruit with a juicy, flirtatious sparkle',
   'fallback': 0,
   'tags': ['lychee', 'pink', 'sweet', 'juicy', 'flirty', 'fruit', 'edible', 'sugar', 'fruit skin']},
  {'name': 'Gardenia',
   'role': 'heart',
   'description': 'creamy white floral with a lush, intoxicating warmth',
   'fallback': 0,
   'tags': ['gardenia', 'creamy', 'white floral', 'lush', 'tropical', 'sensual', 'white petals', 'green stems']},
  {'name': 'Hinoki',
   'role': 'base',
   'description': 'dry hinoki cypress with cool wood and light smoke',
   'fallback': 0,
   'tags': ['hinoki', 'woody', 'smoky', 'meditative', 'japanese', 'forest', 'spa', 'dry wood', 'tree bark']},
  {'name': 'Caramel',
   'role': 'base',
   'description': 'rich caramel with butter, brown sugar, and warm vanilla',
   'fallback': 0,
   'tags': ['caramel', 'gourmand', 'sweet', 'warm', 'golden', 'buttery', 'edible', 'sugar']},
  {'name': 'Cinnamon',
   'role': 'heart',
   'description': 'warm red-brown spice with a cozy, festive pulse',
   'fallback': 0,
   'tags': ['cinnamon', 'spicy', 'warm spice', 'cozy', 'festive', 'baking', 'dry spice', 'aromatic']},
  {'name': 'Cotton',
   'role': 'heart',
   'description': 'soft woven air with a clean, sun-dried simplicity',
   'fallback': 0,
   'tags': ['cotton', 'clean', 'soft', 'linen', 'white shirt', 'airy', 'clean skin', 'soft fabric']},
  {'name': 'Solar Note',
   'role': 'top',
   'description': 'warm solar notes with clean skin musk and soft coconut',
   'fallback': 0,
   'tags': ['solar', 'sunlit', 'warm', 'skin', 'bright', 'luminous', 'clean skin', 'soft fabric']},
  {'name': 'Rhubarb',
   'role': 'top',
   'description': 'tart pink-green stalk with a sharp, mouthwatering bite',
   'fallback': 0,
   'tags': ['rhubarb', 'tart', 'green', 'pink', 'bright', 'fresh', 'green stems', 'crushed leaves', 'fruit skin']},
  {'name': 'Tobacco',
   'role': 'base',
   'description': 'warm dried leaf with honeyed smoke and leather depth',
   'fallback': 0,
   'tags': ['tobacco', 'smoky', 'leather', 'warm', 'honey', 'rich', 'smoldering', 'charred', 'edible']},
  {'name': 'Rice Powder',
   'role': 'heart',
   'description': 'soft rice powder with pale florals and clean musk',
   'fallback': 0,
   'tags': ['rice powder', 'powdery', 'soft', 'elegant', 'vintage', 'cosmetic', 'rice starch', 'soft powder']},
  {'name': 'Wisteria',
   'role': 'heart',
   'description': 'cascading purple floral with a soft, dreamy haze',
   'fallback': 0,
   'tags': ['wisteria', 'purple', 'floral', 'dreamy', 'soft', 'spring', 'petals', 'flower shop']},
  {'name': 'Cypress',
   'role': 'heart',
   'description': 'dry cypress wood with green needles and resin',
   'fallback': 0,
   'tags': ['cypress', 'green', 'woody', 'mediterranean', 'dry', 'forest', 'green stems', 'crushed leaves', 'dry wood']},
  {'name': 'Davana',
   'role': 'heart',
   'description': 'fruity davana with herbal tea, dry wood, and warm fruit',
   'fallback': 0,
   'tags': ['davana', 'fruity', 'herbal', 'artistic', 'bohemian', 'warm', 'green stems', 'crushed leaves']},
  {'name': 'Frankincense',
   'role': 'base',
   'description': 'sacred resin smoke with a clear, meditative lift',
   'fallback': 0,
   'tags': ['frankincense', 'resinous', 'incense', 'meditative', 'clean', 'ritual', 'smoldering', 'charred', 'clean skin']},
  {'name': 'Beeswax',
   'role': 'base',
   'description': 'warm beeswax with honey, pollen, and soft resin',
   'fallback': 0,
   'tags': ['beeswax', 'honey', 'warm', 'golden', 'comforting', 'waxy', 'edible', 'sugar']},
  {'name': 'Tomato Leaf',
   'role': 'top',
   'description': 'sharp green stem with a sun-warmed garden bite',
   'fallback': 0,
   'tags': ['tomato leaf', 'green', 'garden', 'sharp', 'fresh', 'botanical', 'green stems', 'crushed leaves']},
  {'name': 'Salted Caramel',
   'role': 'base',
   'description': 'sweet-salty gourmand warmth with a modern edge',
   'fallback': 0,
   'tags': ['salted caramel', 'gourmand', 'sweet', 'salty', 'warm', 'modern', 'edible', 'sugar']},
  {'name': 'White Musk',
   'role': 'base',
   'description': 'clean translucent musk with a soft, intimate purity',
   'fallback': 0,
   'tags': ['white musk', 'clean', 'skin', 'soft', 'intimate', 'powdery', 'clean skin', 'soft fabric']},
  {'name': 'Bamboo',
   'role': 'top',
   'description': 'green watery freshness with a minimalist, zen calm',
   'fallback': 0,
   'tags': ['bamboo', 'green', 'water', 'minimal', 'zen', 'fresh', 'wet air', 'wet stone', 'green stems']},
  {'name': 'Cotton Candy',
   'role': 'top',
   'description': 'airy spun sugar with a playful, carnival sweetness',
   'fallback': 0,
   'tags': ['cotton candy', 'sweet', 'playful', 'pink', 'carnival', 'gourmand', 'edible', 'sugar']},
]
