"""Aesthetic and internet-style vibe aliases."""

from __future__ import annotations


AESTHETIC_ALIASES = {
    "grunge": ["smoke", "leather", "patchouli", "black", "dusty", "angry", "cedar"],
    "dreamcore": ["dreamy", "soft focus", "pastel", "cloud musk", "iris", "airy", "liminal"],
    "weirdcore": ["surreal", "electric", "plastic", "ozone", "metallic", "anxious", "neon"],
    "avant-garde": ["abstract", "metallic", "aldehydes", "incense", "bitter", "futuristic", "black"],
    "liminal": ["liminal", "empty", "fluorescent", "ozone", "concrete", "quiet", "musk"],
    "cottagecore": ["garden", "hay", "honey", "lavender", "green", "comforting", "spring"],
    "dark academia": ["paper", "black tea", "cedar", "incense", "leather", "nostalgic", "library"],
    "light academia": ["paper", "white tea", "neroli", "clean", "sunlit", "iris", "library"],
    "goth": ["black", "incense", "rose", "patchouli", "smoke", "myrrh", "velvet"],
    "cyberpunk": ["neon", "metallic", "ozone", "electric", "smoke", "city lights", "synthetic"],
    "vaporwave": ["neon", "pastel", "coconut", "ozone", "synthetic", "pink", "blue"],
    "fairycore": ["mossy", "violet", "green", "rain", "wildflower", "dreamy", "forest"],
    "coquette": ["pink", "rose", "powdery", "vanilla", "peony", "soft", "flirty"],
    "clean girl": ["clean", "white shirt", "musk", "neroli", "minimal", "skin", "polished"],
    "old money": ["polished", "iris", "cedar", "white shirt", "luxury", "sandalwood", "elegant"],
    "brutalist": ["concrete", "mineral", "gray", "metallic", "dry", "minimal", "cold"],
    "maximalist": ["bold", "tuberose", "saffron", "plum", "amber", "spicy", "luminous"],
    "minimalist": ["minimal", "clean", "white tea", "musk", "quiet", "clear", "soft"],
    "bohemian": ["patchouli", "amber", "incense", "fig leaf", "earthy", "warm", "smoky"],
    "noir": ["black", "smoke", "leather", "plum", "night", "mysterious", "rain"],
    "ethereal": ["airy", "cloud musk", "iris", "white amber", "soft", "dreamy", "luminous"],
    "industrial": ["metallic", "concrete", "smoke", "gunmetal", "ozone", "gray", "cold"],
    "romcom": ["romantic", "happy", "pink", "peony", "sparkling", "vanilla", "date night"],
    "editorial": ["avant-garde", "iris", "metallic", "saffron", "black", "abstract", "polished"],
    "soft girl": ["pink", "vanilla", "peony", "pear skin", "clean", "sweet", "soft"],
    "dark feminine": ["plum", "rose", "smoke", "leather", "black", "velvet", "night out"],
    "old hollywood": ["lipstick", "iris", "satin", "rose", "powdery", "luxury", "elegant"],
    "coastal grandmother": ["linen", "sea salt", "white tea", "clean", "sunlit", "musk", "airy"],
    "office siren": ["iris", "lipstick", "satin", "black tea", "metallic", "polished", "editorial"],
    "techwear": ["ozone", "metallic", "gunmetal", "concrete", "black", "synthetic", "futuristic"],
    "indie sleaze": ["smoke", "leather", "patchouli", "berry", "neon", "night out", "bold"],
    "goblincore": ["mossy", "wet soil", "oakmoss", "forest", "green", "earthy", "wildflower"],
    "regencycore": ["rose", "peony", "iris", "white amber", "satin", "elegant", "romantic"],
    "y2k": ["neon", "pink", "coconut", "ozone", "glossy", "synthetic", "bright"],
    "fairygrunge": ["smoke", "wildflower", "violet", "mossy", "pear skin", "dreamy", "grunge"],
    "monochrome": ["white tea", "black", "musk", "concrete", "minimal", "clean", "quiet"],
    "dopamine dressing": ["citrus", "pink", "yuzu", "champagne accord", "bright", "colorful", "sparkling"],
    "art hoe": ["ink", "violet", "paper", "iris", "artistic", "abstract", "nostalgic"],
    "glassmorphism": ["white tea", "aldehydes", "ozone", "clean", "transparent", "airy", "soft"],
    "new romantic": ["rose", "jasmine", "satin", "vanilla", "amber", "romantic", "luminous"],
    "quiet luxury": ["iris", "sandalwood", "musk", "white shirt", "cashmeran", "cedarwood", "polished"],
    "surrealist": ["absinthe", "ozone", "metallic", "dreamy", "weird", "mysterious", "electric"],
    "brutalist minimal": ["concrete", "gray", "mineral", "dry", "minimal", "cold", "architecture"],
    "neon noir": ["neon", "smoke", "black", "electric", "city lights", "night", "bold"],
    "slow living": ["linen", "white tea", "clean", "sunlit", "musk", "quiet", "soft"],
    "romantic goth": ["rose", "smoke", "black", "velvet", "incense", "luxe", "dark"],
    "sunbleached": ["linen", "coconut", "sea salt", "white tea", "bright", "airy", "sand"],
    "soft brutalism": ["concrete", "linen", "gray", "musk", "minimal", "polished", "cold"],
    "motelcore": ["ozone", "concrete", "smoke", "neon", "night drive", "liminal", "restless"],
    "apartmentcore": ["linen", "musk", "paper", "clean", "quiet", "minimal", "white shirt"],
    "desert modern": ["sand", "mineral", "cedar", "amber", "dry heat", "minimal", "sunbaked"],
    "romantic realism": ["rose", "iris", "white tea", "paper", "soft", "polished", "quiet"],
    "zen": ["bamboo", "green tea", "white tea", "minimal", "calm", "quiet", "spa"],
    "wabi sabi": ["paper", "cedar", "muted", "imperfect", "quiet", "minimal", "earthy"],
    "cafe core": ["coffee", "vanilla", "paper", "warm", "comforted", "cinnamon", "quiet"],
    "rainy day": ["rain", "petrichor", "gray", "musk", "quiet", "comforted", "paper"],
    "solarpunk": ["solar", "green", "bright", "sunlit", "fresh", "hopeful", "clean"],
    "night drive": ["ozone", "metallic", "concrete", "night", "restless", "city lights", "neon"],
    "beach day": ["coconut", "sea salt", "marine", "sunlit", "bright", "solar", "beach"],
    "forest walk": ["pine", "oakmoss", "cedar", "earthy", "green", "fresh air", "wet soil"],
    "garden party": ["peony", "rose", "green", "sunlit", "floral", "champagne accord", "airy"],
    "mountain retreat": ["pine", "cedar", "fresh air", "mineral", "cold", "quiet", "juniper"],
    "desert dawn": ["desert", "sunrise", "mineral", "sage", "dry", "golden", "quiet"],
    "city rain": ["concrete", "rain", "ozone", "gray", "metallic", "urban", "asphalt"],
    "cottage garden": ["rose", "lavender", "green", "soil", "honey", "sunlit", "floral"],
    "midnight": ["night", "musk", "dark", "quiet", "smoke", "iris", "velvet"],
    "golden hour": ["amber", "honey", "warm", "golden", "sunlit", "solar", "comforting"],
    "indie folk": ["cedar", "paper", "honey", "warm", "nostalgic", "forest", "soft"],
    "balletcore": ["pink", "satin", "peony", "powdery", "soft", "vanilla", "romantic"],
    "mermaidcore": ["marine", "sea salt", "ozone", "pearl", "blue", "shimmering", "aquatic"],
    "dark coquette": ["black", "rose", "cherry", "vanilla", "velvet", "smoke", "flirty"],
    "whimsigoth": ["violet", "incense", "mossy", "moonlight", "velvet", "mysterious", "dreamy"],
    "naturecore": ["forest", "green", "mossy", "rain", "wildflower", "fresh air", "earthy"],
    "angelcore": ["white", "cloud musk", "iris", "soft", "luminous", "clean", "airy"],
}
