"""Color-based vibe aliases."""

from __future__ import annotations


COLOR_ALIASES = {
    "red": ["red", "rose", "pink pepper", "plum", "spicy", "romantic", "bold"],
    "pink": ["pink", "peony", "cherry blossom", "rose", "soft", "flirty"],
    "orange": ["orange", "mandarin", "neroli", "citrus", "bright", "warm"],
    "yellow": ["yellow", "lemon", "honey", "bright", "sunlit", "happy"],
    "gold": ["gold", "golden", "amber", "honey", "saffron", "luxury", "warm"],
    "green": ["green", "fig leaf", "basil", "matcha", "forest", "herbal"],
    "blue": ["blue", "cool", "marine", "rain", "melancholy", "ozone", "sad"],
    "navy": ["navy", "night", "marine", "mysterious", "amber", "clean"],
    "purple": ["purple", "violet", "iris", "plum", "dreamy", "powdery"],
    "violet": ["violet", "iris", "powdery", "soft", "nostalgic", "floral"],
    "black": ["black", "dark", "smoke", "leather", "incense", "patchouli"],
    "white": ["white", "clean", "musk", "white shirt", "neroli", "snow"],
    "peach": ["peach", "osmanthus", "pink", "soft", "warm", "sweet"],
    "coral": ["coral", "pink", "orange", "bright", "flirty", "sunlit"],
    "mint": ["mint", "green tea", "fresh", "cool", "clean", "airy"],
    "olive": ["olive", "green", "herbal", "earthy", "sage", "dry"],
    "charcoal": ["charcoal", "smoke", "gray", "dark", "concrete", "mysterious"],
    "beige": ["beige", "linen", "musk", "sand", "white tea", "minimal"],
    "teal": ["teal", "marine", "ozone", "green", "fresh", "aquatic"],
    "burgundy": ["burgundy", "plum", "rose", "smoke", "velvet", "amber"],
    "silver": ["silver", "aldehydes", "metallic", "futuristic", "clean", "ozone"],
    "grey": ["grey", "gray", "rain", "musk", "concrete", "muted", "mineral"],
    "gray": ["gray", "grey", "rain", "musk", "concrete", "muted", "mineral"],
    "ivory": ["ivory", "white tea", "musk", "clean", "satin", "polished"],
    "blush": ["blush", "pink", "peony", "rose", "soft", "powdery"],
    "brown": ["brown", "cedar", "cocoa", "tonka bean", "earthy", "warm"],
    "tan": ["tan", "sand", "cedar", "warm", "dry", "earthy"],
    "cream": ["cream", "vanilla", "sandalwood", "milk accord", "soft", "comforted"],
    "clear": ["clear", "clean", "water", "ozone", "minimal", "fresh"],
    "sky blue": ["sky blue", "ozone", "airy", "marine", "clean", "fresh"],
    "silver blue": ["silver blue", "aldehydes", "ozone", "marine", "clean", "airy"],
    "cobalt": ["cobalt", "blue", "ozone", "electric", "night", "bold"],
    "neon": ["neon", "electric", "metallic", "grapefruit", "pink pepper", "futuristic"],
    "pastel": ["pastel", "soft", "powdery", "peony", "cherry blossom", "airy"],
    "black velvet": ["black", "velvet", "plum", "incense", "rose", "dark"],
    "white winter": ["white", "winter", "snow", "musk", "clean", "frost"],
    "lavender": ["lavender", "violet", "iris", "soft", "calm", "powdery", "dreamy"],
    "rose gold": ["rose", "golden", "amber", "pink", "warm", "luxury", "luminous"],
    "emerald": ["green", "fig leaf", "forest", "mossy", "herbal", "rich", "earthy"],
    "amber": ["amber", "golden", "warm", "vanilla", "luxury", "resinous", "sensual"],
    "lilac": ["violet", "iris", "powdery", "floral", "soft", "spring", "dreamy"],
    "aqua": ["marine", "ozone", "water", "fresh", "clean", "airy", "blue"],
}
