"""Emotion-based vibe aliases."""

from __future__ import annotations


EMOTION_ALIASES = {
    "sad": ["sad", "melancholy", "lonely", "quiet", "muted", "rain", "iris", "violet", "musk"],
    "depressed": ["sad", "melancholy", "quiet", "muted", "rain", "comforted"],
    "lonely": ["lonely", "quiet", "skin", "musk", "rain", "night"],
    "heartbroken": ["heartbroken", "sad", "rose", "iris", "smoke", "velvet"],
    "grief": ["grief", "incense", "smoke", "iris", "mossy", "dark"],
    "nostalgic": ["nostalgic", "bittersweet", "powdery", "iris", "violet", "vanilla"],
    "bittersweet": ["bittersweet", "orange", "rose", "amber", "soft"],
    "hopeful": ["hopeful", "sunrise", "neroli", "bergamot", "green", "clean"],
    "happy": ["happy", "joyful", "bright", "sparkling", "citrus", "fresh"],
    "joyful": ["joyful", "bright", "sparkling", "orange blossom", "peony", "fresh"],
    "serene": ["serene", "calm", "white tea", "musk", "airy", "quiet"],
    "wistful": ["wistful", "nostalgic", "paper", "violet", "rain", "soft"],
    "euphoric": ["euphoric", "sparkling", "pink pepper", "grapefruit", "luminous"],
    "peaceful": ["peaceful", "calm", "lavender", "tea", "clean", "soft"],
    "calm": ["calm", "green tea", "lavender", "quiet", "spa", "clean"],
    "anxious": ["anxious", "restless", "ginger", "peppery", "ozone", "electric"],
    "restless": ["restless", "night drive", "ozone", "ginger", "metallic"],
    "angry": ["angry", "bold", "smoke", "leather", "peppery", "dark"],
    "confident": ["confident", "bold", "saffron", "leather", "luxury", "cedar"],
    "content": ["content", "soft", "white tea", "musk", "warm", "quiet"],
    "tender": ["tender", "rose", "peony", "musk", "soft", "skin"],
    "playful": ["playful", "sparkling", "pink", "citrus", "joyful", "bright"],
    "detached": ["detached", "white tea", "cold", "minimal", "concrete", "quiet"],
    "safe": ["safe", "comforted", "vanilla", "musk", "linen", "warm"],
    "ashamed": ["ashamed", "pink", "powdery", "quiet", "soft", "skin"],
    "desperate": ["desperate", "smoke", "black", "dark", "amber", "restless"],
    "grateful": ["grateful", "honey", "white tea", "bright", "soft", "sunrise"],
    "sensual": ["sensual", "skin", "amber", "vanilla", "jasmine", "sandalwood"],
    "dreamy": ["dreamy", "soft focus", "luminous", "musk", "iris", "airy"],
    "mysterious": ["mysterious", "incense", "dark", "smoke", "labdanum", "night"],
    "comforted": ["comforted", "comforting", "vanilla", "tonka bean", "cocoa", "soft"],
    "vulnerable": ["vulnerable", "skin", "musk", "quiet", "soft", "iris"],
    "jealous": ["green", "bitter", "sharp", "metallic", "rose", "dark"],
    "homesick": ["nostalgic", "comforted", "paper", "vanilla", "cedar", "soft"],
    "embarrassed": ["pink", "powdery", "skin", "soft", "musk", "quiet"],
    "curious": ["sparkling", "green", "ginger", "tea", "bright", "electric"],
    "focused": ["clean", "cedar", "mint", "white tea", "minimal", "sharp"],
    "burned out": ["smoke", "rain", "musk", "muted", "comforted", "quiet"],
    "overwhelmed": ["anxious", "ozone", "ginger", "lavender", "musk", "calm"],
    "in love": ["romantic", "rose", "jasmine", "vanilla", "amber", "skin"],
    "homesafe": ["comforted", "vanilla", "rice steam", "milk accord", "soft", "warm"],
}
