"""Emotion-based vibe aliases."""

from __future__ import annotations


EMOTION_ALIASES = {
    "sad": ["sad", "melancholy", "lonely", "quiet", "muted", "rain", "iris", "violet", "musk"],
    "depressed": ["sad", "melancholy", "quiet", "muted", "rain", "comforted"],
    "lonely": ["lonely", "quiet", "skin", "musk", "rain", "night"],
    "heartbroken": ["heartbroken", "sad", "rose", "iris", "smoke", "velvet"],
    "grief": ["grief", "incense", "smoke", "iris", "mossy", "dark"],
    "nostalgic": ["nostalgic", "bittersweet", "powdery", "iris", "violet", "vanilla"],
    "bittersweet": ["bittersweet", "orange", "rose", "amber", "soft"],
    "hopeful": ["hopeful", "sunrise", "neroli", "bergamot", "green", "clean"],
    "happy": ["happy", "joyful", "bright", "sparkling", "citrus", "fresh"],
    "joyful": ["joyful", "bright", "sparkling", "orange blossom", "peony", "fresh"],
    "serene": ["serene", "calm", "white tea", "musk", "airy", "quiet"],
    "wistful": ["wistful", "nostalgic", "paper", "violet", "rain", "soft", "quiet"],
    "euphoric": ["euphoric", "sparkling", "pink pepper", "grapefruit", "luminous"],
    "peaceful": ["peaceful", "calm", "lavender", "tea", "clean", "soft"],
    "calm": ["calm", "green tea", "lavender", "quiet", "spa", "clean"],
    "anxious": ["anxious", "restless", "ginger", "peppery", "ozone", "electric"],
    "restless": ["restless", "night drive", "ozone", "ginger", "metallic"],
    "angry": ["angry", "bold", "smoke", "leather", "peppery", "dark"],
    "confident": ["confident", "bold", "saffron", "leather", "luxury", "cedar"],
    "content": ["content", "soft", "white tea", "musk", "warm", "quiet", "calm"],
    "tender": ["tender", "rose", "peony", "musk", "soft", "skin", "warm"],
    "playful": ["playful", "sparkling", "pink", "citrus", "joyful", "bright", "flirty"],
    "detached": ["detached", "white tea", "cold", "minimal", "concrete", "quiet", "muted"],
    "safe": ["safe", "comforted", "vanilla", "musk", "linen", "warm", "soft"],
    "ashamed": ["ashamed", "pink", "powdery", "quiet", "soft", "skin", "musk"],
    "desperate": ["desperate", "smoke", "black", "dark", "amber", "restless", "burnt sugar"],
    "grateful": ["grateful", "honey", "white tea", "bright", "soft", "sunrise", "warm"],
    "sensual": ["sensual", "skin", "amber", "vanilla", "jasmine", "sandalwood"],
    "dreamy": ["dreamy", "soft focus", "luminous", "musk", "iris", "airy"],
    "mysterious": ["mysterious", "incense", "dark", "smoke", "labdanum", "night"],
    "comforted": ["comforted", "comforting", "vanilla", "tonka bean", "cocoa", "soft"],
    "vulnerable": ["vulnerable", "skin", "musk", "quiet", "soft", "iris"],
    "jealous": ["jealous", "green", "bitter", "sharp", "metallic", "rose", "dark"],
    "homesick": ["homesick", "nostalgic", "comforted", "paper", "vanilla", "cedar", "soft"],
    "embarrassed": ["embarrassed", "pink", "powdery", "skin", "soft", "musk", "quiet"],
    "curious": ["curious", "sparkling", "green", "ginger", "tea", "bright", "electric"],
    "focused": ["focused", "clean", "cedar", "mint", "white tea", "minimal", "sharp"],
    "burned out": ["burned out", "smoke", "rain", "musk", "muted", "comforted", "quiet"],
    "overwhelmed": ["overwhelmed", "anxious", "ozone", "ginger", "lavender", "musk", "calm"],
    "in love": ["in love", "romantic", "rose", "jasmine", "vanilla", "amber", "skin"],
    "homesafe": ["comforted", "vanilla", "rice steam", "milk accord", "soft", "warm"],
    "intense": ["intense", "bold", "oud", "leather", "smoke", "dark", "spicy"],
    "longing": ["longing", "nostalgic", "iris", "violet", "amber", "soft", "quiet"],
    "excited": ["excited", "sparkling", "bright", "citrus", "joyful", "champagne accord", "energetic"],
    "cozy": ["cozy", "warm", "vanilla", "cocoa", "soft", "comforted", "cinnamon"],
    "reflective": ["reflective", "quiet", "paper", "black tea", "iris", "musk", "calm"],
    "melancholic": ["melancholic", "sad", "rain", "violet", "iris", "muted", "nostalgic"],
    "energetic": ["energetic", "bright", "citrus", "ginger", "sparkling", "fresh", "daylight"],
    "numb": ["detached", "cold", "minimal", "concrete", "quiet", "muted", "musk"],
    "empty": ["empty", "liminal", "concrete", "fluorescent", "gray", "quiet", "musk"],
    "fragile": ["vulnerable", "iris", "musk", "powdery", "soft", "quiet", "skin"],
    "restored": ["hopeful", "clean", "fresh", "white tea", "musk", "sunrise", "calm"],
    "free": ["airy", "ozone", "fresh air", "citrus", "bright", "open air", "daylight"],
    "alive": ["energetic", "green", "citrus", "sunlit", "fresh", "sparkling", "warm"],
}
