"""Relationship and verb-like expression aliases."""

from __future__ import annotations


EXPRESSION_ALIASES = {
    "love": ["romantic", "in love", "rose", "jasmine", "amber", "vanilla", "skin"],
    "i love you": ["romantic", "in love", "rose", "jasmine", "amber", "vanilla", "skin"],
    "kiss": ["romantic", "in love", "rose", "jasmine", "skin", "vanilla", "sensual"],
    "kiss me": ["romantic", "in love", "rose", "jasmine", "skin", "vanilla", "sensual"],
    "adore": ["romantic", "rose", "jasmine", "soft", "warm", "amber"],
    "miss you": ["homesick", "nostalgic", "paper", "vanilla", "musk", "quiet"],
    "miss": ["homesick", "nostalgic", "paper", "vanilla", "musk", "quiet"],
    "crave": ["sensual", "amber", "vanilla", "saffron", "luminous", "warm"],
    "want": ["confident", "bright", "clean", "amber", "green", "focused"],
    "need": ["focused", "clean", "white tea", "mint", "cedar", "minimal"],
    "yearn": ["longing", "nostalgic", "iris", "violet", "amber", "soft"],
    "longing": ["yearn", "nostalgic", "iris", "violet", "amber", "quiet"],
    "cherish": ["comforted", "vanilla", "rose", "white amber", "soft", "warm"],
    "crush": ["romantic", "peony", "pink pepper", "rose", "vanilla", "skin"],
    "linger": ["skin", "musk", "amber", "smoke", "quiet", "soft focus"],
    "escape": ["ozone", "ocean", "sand", "citrus", "sunlit", "airy"],
    "protect": ["comforted", "sandalwood", "musk", "white amber", "soft", "warm"],
    "obsessed": ["intense", "black", "smoke", "leather", "neon", "night out"],
    "hate": ["black", "smoke", "angry", "leather", "burnt sugar", "dark"],
    "dream": ["dreamy", "cloud musk", "iris", "airy", "pastel", "luminous"],
    "remember": ["nostalgic", "paper", "old books", "vintage", "soft", "quiet"],
    "forget": ["empty", "liminal", "concrete", "fluorescent", "gray", "quiet"],
    "heal": ["comforted", "vanilla", "musk", "white amber", "soft", "warm"],
    "shy": ["pink", "peony", "powdery", "soft", "quiet", "skin"],
    "hug": ["comforted", "soft", "musk", "vanilla", "warm", "skin"],
    "touch": ["skin", "musk", "amber", "suede", "soft", "sensual"],
    "blush": ["pink", "peony", "rose", "powdery", "soft", "flirty"],
    "whisper": ["quiet", "paper", "musk", "white tea", "soft", "airy"],
    "dance": ["sparkling", "night out", "pink pepper", "amber", "joyful", "luminous"],
    "wander": ["ozone", "rain", "cedar", "airy", "curious", "quiet"],
    "breathe": ["clean", "white tea", "eucalyptus", "ozone", "calm", "fresh air"],
    "hold": ["comforted", "skin", "musk", "warm", "soft", "vanilla"],
    "embrace": ["comforted", "skin", "musk", "vanilla", "warm", "sandalwood"],
    "smile": ["happy", "bright", "peony", "citrus", "fresh", "soft"],
    "laugh": ["joyful", "sparkling", "bright", "citrus", "happy", "airy"],
    "cry": ["sad", "rain", "violet", "iris", "musk", "quiet"],
    "run": ["restless", "ozone", "citrus", "fresh air", "fresh", "night drive"],
    "sleep": ["calm", "lavender", "musk", "soft", "quiet", "white tea"],
    "hide": ["quiet", "concrete", "musk", "dark", "liminal", "soft"],
    "forgive": ["comforted", "rose", "white amber", "vanilla", "soft", "warm"],
    "desire": ["sensual", "amber", "vanilla", "jasmine", "saffron", "warm"],
}
