"""Relationship and verb-like expression aliases."""

from __future__ import annotations


EXPRESSION_ALIASES = {
    "love": ["romantic", "in love", "rose", "jasmine", "amber", "vanilla", "skin"],
    "i love you": ["romantic", "in love", "rose", "jasmine", "amber", "vanilla", "skin"],
    "kiss": ["romantic", "in love", "rose", "jasmine", "skin", "vanilla", "sensual"],
    "kiss me": ["romantic", "in love", "rose", "jasmine", "skin", "vanilla", "sensual"],
    "adore": ["romantic", "rose", "jasmine", "soft", "warm", "amber"],
    "miss you": ["homesick", "nostalgic", "paper", "vanilla", "musk", "quiet"],
    "miss": ["homesick", "nostalgic", "paper", "vanilla", "musk", "quiet"],
    "crave": ["sensual", "amber", "vanilla", "saffron", "luminous", "warm"],
    "want": ["confident", "bright", "clean", "amber", "green", "focused"],
    "need": ["focused", "clean", "white tea", "mint", "cedar", "minimal"],
    "yearn": ["longing", "nostalgic", "iris", "violet", "amber", "soft"],
    "longing": ["yearn", "nostalgic", "iris", "violet", "amber", "quiet"],
    "cherish": ["comforted", "vanilla", "rose", "white amber", "soft", "warm"],
    "crush": ["romantic", "peony", "pink pepper", "rose", "vanilla", "skin"],
    "linger": ["skin", "musk", "amber", "smoke", "quiet", "soft focus"],
    "escape": ["ozone", "ocean", "sand", "citrus", "sunlit", "airy"],
    "protect": ["comforted", "sandalwood", "musk", "white amber", "soft", "warm"],
    "obsessed": ["intense", "black", "smoke", "leather", "neon", "night out"],
    "hate": ["black", "smoke", "angry", "leather", "burnt sugar", "dark"],
    "dream": ["dreamy", "cloud musk", "iris", "airy", "pastel", "luminous"],
    "remember": ["nostalgic", "paper", "old books", "vintage", "soft", "quiet"],
    "forget": ["empty", "liminal", "concrete", "fluorescent", "gray", "quiet"],
    "heal": ["comforted", "vanilla", "musk", "white amber", "soft", "warm"],
    "shy": ["pink", "peony", "powdery", "soft", "quiet", "skin"],
    "hug": ["comforted", "soft", "musk", "vanilla", "warm", "skin"],
    "touch": ["skin", "musk", "amber", "suede", "soft", "sensual"],
    "blush": ["pink", "peony", "rose", "powdery", "soft", "flirty"],
    "whisper": ["quiet", "paper", "musk", "white tea", "soft", "airy"],
    "dance": ["sparkling", "night out", "pink pepper", "amber", "joyful", "luminous"],
    "wander": ["ozone", "rain", "cedar", "airy", "curious", "quiet"],
    "breathe": ["clean", "white tea", "eucalyptus", "ozone", "calm", "fresh air"],
    "hold": ["comforted", "skin", "musk", "warm", "soft", "vanilla"],
    "embrace": ["comforted", "skin", "musk", "vanilla", "warm", "sandalwood"],
    "smile": ["happy", "bright", "peony", "citrus", "fresh", "soft"],
    "laugh": ["joyful", "sparkling", "bright", "citrus", "happy", "airy"],
    "cry": ["sad", "rain", "violet", "iris", "musk", "quiet"],
    "run": ["restless", "ozone", "citrus", "fresh air", "fresh", "night drive"],
    "sleep": ["calm", "lavender", "musk", "soft", "quiet", "white tea"],
    "hide": ["quiet", "concrete", "musk", "dark", "liminal", "soft"],
    "forgive": ["comforted", "rose", "white amber", "vanilla", "soft", "warm"],
    "desire": ["sensual", "amber", "vanilla", "jasmine", "saffron", "warm"],
    "fighting": ["angry", "smoke", "peppery", "black pepper", "burnt sugar", "gunmetal", "tension"],
    "fight": ["angry", "smoke", "peppery", "black pepper", "burnt sugar", "gunmetal", "tension"],
    "argue": ["angry", "smoke", "sharp", "peppery", "black pepper", "tension", "dark"],
    "apologize": ["sad", "vulnerable", "musk", "paper", "soft", "quiet", "rain"],
    "sorry": ["sad", "vulnerable", "musk", "paper", "soft", "quiet", "rain"],
    "forgive me": ["vulnerable", "comforted", "vanilla", "white amber", "soft", "warm", "musk"],
    "reconcile": ["comforted", "soft", "musk", "vanilla", "warm", "hope", "clean"],
    "write": ["paper", "ink", "quiet", "focused", "black tea", "cedar", "nostalgic"],
    "writing": ["paper", "ink", "quiet", "focused", "black tea", "cedar", "nostalgic"],
    "read": ["paper", "old books", "quiet", "cedar", "black tea", "cozy", "calm"],
    "reading": ["paper", "old books", "quiet", "cedar", "black tea", "cozy", "calm"],
    "study": ["paper", "cedar", "focused", "mint", "white tea", "clean", "quiet"],
    "studying": ["paper", "cedar", "focused", "mint", "white tea", "clean", "quiet"],
    "wait": ["anxious", "quiet", "ozone", "paper", "muted", "restless", "clean"],
    "waiting": ["anxious", "quiet", "ozone", "paper", "muted", "restless", "clean"],
    "cook": ["warm", "spicy", "ginger", "cinnamon", "gourmand", "vanilla", "herbal"],
    "cooking": ["warm", "spicy", "ginger", "cinnamon", "gourmand", "vanilla", "herbal"],
    "bake": ["vanilla", "cinnamon", "warm", "sweet", "gourmand", "cozy", "buttery"],
    "baking": ["vanilla", "cinnamon", "warm", "sweet", "gourmand", "cozy", "buttery"],
    "garden": ["green", "soil", "herbal", "sunlit", "basil", "tomato leaf", "fresh"],
    "gardening": ["green", "soil", "herbal", "sunlit", "basil", "tomato leaf", "fresh"],
    "walk": ["fresh air", "ozone", "cedar", "green", "clean", "grounded", "calm"],
    "walking": ["fresh air", "ozone", "cedar", "green", "clean", "grounded", "calm"],
    "drive": ["ozone", "night drive", "citrus", "restless", "fresh air", "cedar", "city lights"],
    "driving": ["ozone", "night drive", "citrus", "restless", "fresh air", "cedar", "city lights"],
    "fly": ["ozone", "airy", "bright", "fresh air", "clean", "sparkling", "citrus"],
    "floating": ["ozone", "airy", "bright", "fresh air", "clean", "sparkling", "citrus"],
    "float": ["ozone", "airy", "bright", "fresh air", "clean", "sparkling", "citrus"],
    "swim": ["marine", "ozone", "fresh", "water", "clean", "chlorine", "bright"],
    "swimming": ["marine", "ozone", "fresh", "water", "clean", "chlorine", "bright"],
    "rain": ["rain", "petrichor", "fresh air", "ozone", "melancholy", "clean", "quiet"],
    "raining": ["rain", "petrichor", "fresh air", "ozone", "melancholy", "clean", "quiet"],
    "snow": ["snow", "cold", "frost", "clean", "quiet", "pine", "musk"],
    "snowing": ["snow", "cold", "frost", "clean", "quiet", "pine", "musk"],
    "celebrate": ["champagne accord", "sparkling", "happy", "bright", "joyful", "citrus", "luminous"],
    "celebrating": ["champagne accord", "sparkling", "happy", "bright", "joyful", "citrus", "luminous"],
    "mourn": ["grief", "myrrh", "incense", "quiet", "iris", "smoke", "dark"],
    "mourning": ["grief", "myrrh", "incense", "quiet", "iris", "smoke", "dark"],
    "meditate": ["calm", "incense", "sandalwood", "quiet", "white tea", "clean", "zen"],
    "meditating": ["calm", "incense", "sandalwood", "quiet", "white tea", "clean", "zen"],
    "paint": ["artistic", "turpentine", "linen", "creative", "bright", "abstract", "ink"],
    "painting": ["artistic", "turpentine", "linen", "creative", "bright", "abstract", "ink"],
    "travel": ["ozone", "citrus", "fresh air", "restless", "coconut", "sunlit", "curious"],
    "traveling": ["ozone", "citrus", "fresh air", "restless", "coconut", "sunlit", "curious"],
    "work": ["focused", "coffee", "cedar", "clean", "polished", "white tea", "sharp"],
    "working": ["focused", "coffee", "cedar", "clean", "polished", "white tea", "sharp"],
    "rest": ["calm", "lavender", "musk", "soft", "quiet", "white tea", "comforted"],
    "resting": ["calm", "lavender", "musk", "soft", "quiet", "white tea", "comforted"],
    "party": ["sparkling", "champagne accord", "night out", "happy", "neon", "bright", "bold"],
    "partying": ["sparkling", "champagne accord", "night out", "happy", "neon", "bright", "bold"],
    "date": ["romantic", "rose", "jasmine", "vanilla", "amber", "warm", "luminous"],
    "dating": ["romantic", "rose", "jasmine", "vanilla", "amber", "warm", "luminous"],
}
