"""Food and drink vibe aliases."""

from __future__ import annotations


FOOD_AND_DRINK_ALIASES = {
    "mojito": ["mint", "lime", "citrus", "fresh", "beach", "summer", "sparkling", "green"],
    "margarita": ["citrus", "lime", "salt", "beach", "bright", "summer", "fresh"],
    "espresso martini": ["coffee", "black", "night out", "luxury", "polished", "dark"],
    "champagne": ["champagne accord", "sparkling", "luxury", "bright", "night out", "happy"],
    "wine": ["plum", "red", "velvet", "dark fruit", "romantic", "evening"],
    "whiskey": ["smoke", "oakmoss", "amber", "leather", "dark", "warm"],
    "rum": ["coconut", "vanilla", "beach", "warm", "sweet", "summer"],
    "tea": ["green tea", "black tea", "calm", "quiet", "clean", "soft"],
    "coffee": ["black coffee", "bitter", "focused", "warm", "dark", "morning"],
    "dessert": ["vanilla", "tonka bean", "cocoa", "sweet", "comforted", "gourmand"],
    "lemonade": ["citrus", "bright", "fresh", "sweet", "summer", "sparkling"],
    "cola": ["black", "sweet", "fizzy", "nostalgic", "night", "spicy"],
    "matcha latte": ["green tea", "milk accord", "vanilla", "calm", "creamy", "soft"],
    "iced tea": ["white tea", "citrus", "clean", "fresh", "airy", "calm"],
    "hot chocolate": ["cocoa", "vanilla", "warm", "comforted", "sweet", "cozy"],
    "milk tea": ["tea", "milk accord", "vanilla", "soft", "creamy", "sweet"],
    "prosecco": ["champagne accord", "sparkling", "happy", "bright", "luxury", "fresh"],
    "pina colada": ["coconut", "citrus", "beach", "summer", "sweet", "bright"],
    "iced coffee": ["coffee", "cold", "bitter", "focused", "morning", "clean"],
    "sparkling water": ["ozone", "clean", "citrus", "bright", "fresh", "minimal"],
    "picnic": ["spring", "green", "apple skin", "hay", "fresh", "bright"],
    "brunch": ["bergamot", "honey", "citrus", "happy", "clean", "sunlit"],
    "coffee shop": ["coffee", "paper", "cedar", "quiet", "warm", "nostalgic"],
    "bakery": ["vanilla", "cocoa", "sweet", "warm", "comforted", "gourmand"],
    "street food": ["spicy", "ginger", "citrus", "smoke", "energetic", "bold"],
    "lunch": ["clean", "fresh", "bergamot", "white tea", "happy", "bright"],
    "dinner": ["amber", "jasmine", "sandalwood", "romantic", "warm", "polished"],
    "late night snack": ["cocoa", "vanilla", "comforted", "soft", "sweet", "quiet"],
    "smoothie": ["fruit", "bright", "fresh", "citrus", "sweet", "summer", "green"],
    "sake": ["rice steam", "clean", "soft", "minimal", "calm", "warm", "japanese"],
    "whiskey sour": ["whiskey", "citrus", "smoke", "amber", "sweet", "sour", "night out"],
    "chai": ["cinnamon", "cardamom", "ginger", "warm spice", "sweet", "comforting", "cozy"],
    "lavender latte": ["lavender", "vanilla", "creamy", "calm", "soft", "warm", "sweet"],
    "fruit punch": ["fruit", "sweet", "bright", "tropical", "playful", "colorful", "juicy"],
    "maple syrup": ["maple", "sweet", "gourmand", "warm", "golden", "cozy", "breakfast"],
    "roasted chestnut": ["warm", "nutty", "cozy", "gourmand", "sweet", "autumn", "smoky"],
    "ginger ale": ["ginger", "sparkling", "fresh", "bright", "crisp", "clean", "zesty"],
    "coconut water": ["coconut", "fresh", "clean", "tropical", "water", "light", "summer"],
    "rose latte": ["rose", "vanilla", "creamy", "soft", "romantic", "warm", "floral"],
    "honey tea": ["honey", "tea", "warm", "comforting", "sweet", "calm", "golden"],
    "mulled wine": ["cinnamon", "clove", "warm", "spicy", "red", "cozy", "winter"],
    "cherry soda": ["cherry", "sweet", "sparkling", "bright", "red", "playful", "nostalgic"],
}
