"""Location and landscape vibe aliases."""

from __future__ import annotations


PLACE_ALIASES = {
    "desert": ["desert", "arid", "sand", "sunbaked", "cactus", "dry heat", "mineral", "sage"],
    "dessert": ["vanilla", "tonka bean", "cocoa", "sweet", "gourmand", "comforting"],
    "dunes": ["desert", "sand", "sunbaked", "dry", "mineral", "warm"],
    "canyon": ["desert", "mineral", "dry", "cedar", "sunbaked", "earthy"],
    "chaparral": ["sage", "dry", "herbal", "sunbaked", "green", "earthy"],
    "mountain": ["pine", "cedar", "fresh air", "cold", "forest", "mineral"],
    "forest": ["forest", "pine", "oakmoss", "mossy", "earthy", "green", "cedar"],
    "library": ["paper", "cedar", "quiet", "powdery", "nostalgic", "dry"],
    "beach": ["beach", "sea salt", "coconut", "marine", "sunlit", "clean"],
    "church": ["incense", "myrrh", "quiet", "ritual", "mysterious", "wood"],
    "hospital": ["clean", "aldehydes", "white", "metallic", "quiet", "anxious"],
    "laundromat": ["clean", "musk", "aldehydes", "white", "warm", "comforted"],
    "gas station": ["gasoline", "ozone", "metallic", "night drive", "synthetic", "restless"],
    "parking lot": ["concrete", "ozone", "rain", "gray", "liminal", "night"],
    "mall": ["synthetic", "vanilla", "clean", "neon", "plastic", "nostalgic"],
    "museum": ["iris", "paper", "polished", "quiet", "abstract", "cool"],
    "rooftop": ["ozone", "city lights", "bright", "night out", "metallic", "airy"],
    "bookstore": ["paper", "cedar", "quiet", "nostalgic", "dusty", "warm"],
    "cafeteria": ["clean", "school", "bright", "plastic", "nostalgic", "daylight"],
    "beach house": ["beach", "coconut", "sea salt", "linen", "sunlit", "cedar"],
    "warehouse": ["concrete", "metallic", "industrial", "gray", "dusty", "cold"],
    "balcony": ["airy", "sunlit", "city lights", "white tea", "clean", "fresh air"],
    "train platform": ["metallic", "concrete", "ozone", "rain", "liminal", "gray"],
    "corner store": ["plastic", "clean", "fluorescent", "sweet", "night", "nostalgic"],
    "parking garage": ["concrete", "gray", "ozone", "night", "industrial", "liminal"],
    "train station": ["metallic", "concrete", "ozone", "rain", "gray", "liminal"],
    "apartment": ["clean", "cedar", "musk", "paper", "quiet", "minimal"],
    "garden party": ["peony", "rose", "champagne accord", "sunlit", "airy", "floral"],
    "arcade": ["neon", "electric", "plastic", "sweet", "sparkling", "night"],
    "subway": ["metallic", "concrete", "ozone", "smoke", "urban", "gray"],
    "hotel lobby": ["polished", "white tea", "amber", "clean", "luxury", "musk"],
    "greenhouse": ["humid", "green", "fig leaf", "soil", "floral", "rain"],
    "attic": ["dusty", "paper", "cedar", "nostalgic", "dry", "quiet"],
    "basement": ["concrete", "mossy", "damp", "gray", "earthy", "mysterious"],
    "hallway": ["liminal", "fluorescent", "clean", "ozone", "concrete", "quiet"],
}
