"""Scenario and occasion vibe aliases."""

from __future__ import annotations


SCENARIO_ALIASES = {
    "classroom": ["paper", "cedar", "morning", "clean", "nostalgic", "quiet"],
    "school": ["paper", "cedar", "morning", "clean", "nostalgic", "quiet"],
    "early classroom": ["paper", "morning", "quiet", "clean", "sunrise", "nostalgic"],
    "classroom morning": ["paper", "morning", "sunrise", "clean", "nostalgic", "cedar"],
    "job interview": ["confident", "polished", "white shirt", "clean", "cedar", "bergamot", "musk"],
    "interview": ["confident", "polished", "white shirt", "clean", "cedar", "bergamot"],
    "first day": ["anxious", "hopeful", "clean", "white shirt", "bergamot", "cedar"],
    "office": ["polished", "white shirt", "clean", "cedar", "minimal", "confident"],
    "breakup": ["heartbroken", "rose", "rain", "smoke", "iris", "musk"],
    "final exam": ["anxious", "paper", "mint", "cedar", "clean", "focused"],
    "prom night": ["romantic", "sparkling", "rose", "vanilla", "pink", "night out"],
    "road trip": ["night drive", "ozone", "cedar", "citrus", "amber", "restless"],
    "first kiss": ["romantic", "rose", "jasmine", "vanilla", "skin", "sensual"],
    "study hall": ["paper", "cedar", "white tea", "quiet", "focused", "minimal"],
    "moving day": ["paper", "clean", "cedar", "musk", "fresh", "minimal"],
    "rainy commute": ["rain", "ozone", "concrete", "gray", "quiet", "fresh air"],
    "coffee date": ["coffee", "romantic", "amber", "vanilla", "warm", "polished"],
    "night shift": ["ozone", "coffee", "metallic", "dark", "quiet", "restless"],
    "birthday dinner": ["birthday cake", "champagne accord", "rose", "vanilla", "party", "warm"],
    "summer night": ["coconut", "jasmine", "amber", "night out", "airy", "warm"],
    "club night": ["neon", "smoke", "electric", "champagne accord", "bold", "night out"],
    "sleepover": ["comforted", "vanilla", "milk accord", "pastel", "musk", "happy"],
    "gallery opening": ["avant-garde", "iris", "champagne accord", "polished", "metallic", "black"],
    "after party": ["smoke", "skin", "amber", "night", "champagne accord", "messy"],
    "wedding guest": ["rose", "satin", "champagne accord", "peony", "polished", "romantic"],
    "museum date": ["iris", "paper", "quiet", "polished", "black tea", "abstract"],
    "late train": ["ozone", "concrete", "rain", "metallic", "night", "quiet"],
    "new apartment": ["clean", "white tea", "cedarwood", "linen", "soft", "minimal"],
    "summer festival": ["neon", "citrus", "smoke", "champagne accord", "night out", "bright"],
    "morning commute": ["coffee", "ozone", "fresh air", "clean", "cedar", "daylight"],
    "evening walk": ["dusk", "fresh air", "quiet", "musk", "night air", "soft"],
    "afternoon nap": ["calm", "soft", "musk", "linen", "quiet", "comforted", "sunlit"],
    "grocery store": ["clean", "fluorescent", "citrus", "fresh", "plastic", "bright"],
    "laundry day": ["clean", "musk", "cotton", "fresh air", "white musk", "linen"],
    "waiting room": ["clean", "paper", "quiet", "ozone", "muted", "anxious", "minimal"],
    "airport": ["ozone", "metallic", "clean", "restless", "concrete", "synthetic", "bright"],
    "farmers market": ["green", "citrus", "garden", "soil", "herbal", "sunlit", "fresh"],
    "rainy afternoon": ["rain", "petrichor", "gray", "quiet", "comforted", "paper", "tea"],
    "snowy evening": ["snow", "cold", "quiet", "musk", "pine", "vanilla", "warm"],
    "spring morning": ["sunrise", "green", "fresh", "floral", "dew", "bright", "hopeful"],
    "autumn evening": ["amber", "cedar", "smoke", "golden", "quiet", "warm", "cocoa"],
    "winter morning": ["snow", "cold", "pine", "fresh air", "clean", "quiet", "frost"],
    "summer afternoon": ["sunlit", "bright", "coconut", "marine", "warm", "solar", "citrus"],
    "first fight": ["angry", "smoke", "burnt sugar", "gunmetal", "tension", "black pepper", "sad"],
    "our first fight": ["angry", "smoke", "burnt sugar", "gunmetal", "tension", "black pepper", "sad"],
    "writing a letter": ["paper", "ink", "quiet", "nostalgic", "black tea", "cedar", "focused"],
    "reading a book": ["paper", "old books", "quiet", "cedar", "cozy", "calm", "black tea"],
    "cooking dinner": ["warm", "spicy", "ginger", "cinnamon", "gourmand", "vanilla", "herbal"],
    "morning coffee": ["coffee", "morning", "sunrise", "clean", "focused", "warm", "bergamot"],
    "evening tea": ["black tea", "evening", "calm", "quiet", "warm", "comforted", "soft"],
    "late night drive": ["night drive", "ozone", "restless", "metallic", "city lights", "neon", "dark"],
    "rainy day": ["rain", "petrichor", "gray", "quiet", "comforted", "paper", "melancholy"],
    "snowy day": ["snow", "cold", "quiet", "musk", "pine", "vanilla", "clean"],
    "beach day": ["coconut", "sea salt", "marine", "sunlit", "bright", "solar", "beach"],
    "garden walk": ["green", "herbal", "sunlit", "fresh", "soil", "floral", "calm"],
    "first date": ["romantic", "anxious", "hopeful", "rose", "vanilla", "sparkling", "clean"],
    "breakfast in bed": ["coffee", "vanilla", "warm", "comforted", "sunrise", "soft", "honey"],
    "sunset walk": ["dusk", "golden", "amber", "quiet", "fresh air", "warm", "soft"],
    "midnight snack": ["cocoa", "vanilla", "warm", "comforted", "soft", "quiet", "gourmand"],
    "morning run": ["fresh air", "ozone", "citrus", "energetic", "clean", "bright", "daylight"],
    "afternoon tea": ["white tea", "calm", "quiet", "soft", "sunlit", "clean", "elegant"],
    "bonfire night": ["smoke", "bonfire", "night", "warm", "amber", "woody", "dark"],
    "hot bath": ["steam", "lavender", "calm", "warm", "clean", "soft", "eucalyptus"],
    "fresh laundry": ["cotton", "clean", "musk", "fresh air", "linen", "white musk", "soft"],
    "new beginning": ["hopeful", "bright", "clean", "citrus", "fresh", "sunrise", "bergamot"],
    "goodbye": ["nostalgic", "sad", "paper", "iris", "vanilla", "quiet", "musk"],
    "welcome home": ["comforted", "warm", "vanilla", "musk", "soft", "clean", "amber"],
}
