"""Season and weather vibe aliases."""

from __future__ import annotations


SEASON_ALIASES = {
    "spring": ["spring", "green", "peony", "cherry blossom", "fresh", "rain"],
    "summer": ["summer", "coconut", "sea salt", "citrus", "bright", "beach"],
    "autumn": ["autumn", "fall", "cedar", "amber", "cocoa", "dry", "spicy"],
    "fall": ["fall", "autumn", "cedar", "amber", "cocoa", "dry", "spicy"],
    "winter": ["winter", "snow", "frost", "cold", "pine", "vanilla", "musk"],
    "snow": ["snow", "frost", "cold", "clean", "musk", "pine"],
    "sunrise": ["sunrise", "bergamot", "yuzu", "mandarin", "honey", "neroli", "peony", "coconut", "white amber", "gold"],
    "rainy": ["rain", "petrichor", "fresh air", "melancholy", "green"],
    "stormy": ["ozone", "rain", "smoke", "dark", "electric", "restless"],
    "foggy": ["musk", "gray", "rain", "quiet", "liminal", "soft"],
    "humid": ["humid", "tropical", "jasmine", "green", "coconut", "marine"],
    "golden hour": ["amber", "bergamot", "honey", "yuzu", "warm", "luminous"],
    "spring rain": ["green", "peony", "rain", "fresh", "dreamy", "floral"],
    "late summer": ["coconut", "sea salt", "fig leaf", "amber", "sunlit", "warm"],
    "deep winter": ["snow", "pine", "smoke", "vanilla", "cold", "quiet"],
    "rainy morning": ["rain", "coffee", "cedar", "calm", "muted", "fresh"],
    "early spring": ["peony", "green", "white tea", "rain", "fresh", "soft"],
    "late autumn": ["amber", "cedar", "cocoa", "dry", "soft", "golden"],
    "spring afternoon": ["sunlit", "green", "citrus", "airy", "floral", "fresh"],
    "first frost": ["snow", "musk", "pine", "cold", "quiet", "clean"],
    "overcast": ["gray", "rain", "musk", "quiet", "muted", "soft"],
    "windy": ["airy", "ozone", "fresh air", "clean", "cold", "bright"],
    "humid night": ["humid", "jasmine", "coconut", "marine", "night", "soft"],
    "summer rain": ["rain", "citrus", "fresh air", "green", "warm", "bright"],
    "moonlight": ["moonlight", "moonlit", "silver", "white amber", "iris", "musk", "luminous"],
    "moonlit": ["moonlight", "moonlit", "silver", "white amber", "iris", "musk", "luminous"],
    "twilight": ["twilight", "violet", "iris", "amber", "musk", "quiet"],
    "dusk": ["dusk", "amber", "smoke", "violet", "night", "soft"],
    "starlight": ["starlight", "aldehydes", "silver", "sparkling", "airy", "luminous"],
    "nightfall": ["nightfall", "smoke", "musk", "concrete", "quiet", "dark"],
    "dry season": ["dry season", "dry", "sunbaked", "cedar", "vetiver", "desert"],
    "heatwave": ["dry heat", "sunbaked", "citrus", "ginger", "amber", "restless"],
    "monsoon": ["rain", "humid", "jasmine", "petrichor", "green", "ozone"],
    "early autumn": ["amber", "cedar", "cocoa", "dry", "golden", "spicy", "soft"],
    "mid winter": ["snow", "cold", "pine", "quiet", "vanilla", "smoke", "frost"],
    "spring bloom": ["peony", "cherry blossom", "green", "floral", "fresh", "soft", "pollen"],
    "autumn leaves": ["dry", "golden", "cedar", "smoke", "crisp", "earthy", "amber"],
    "summer dusk": ["coconut", "jasmine", "amber", "warm", "night air", "soft", "marine"],
    "winter night": ["snow", "cold", "quiet", "musk", "starlight", "dark", "pine"],
    "spring drizzle": ["rain", "green", "fresh", "petrichor", "soft", "floral", "clean"],
}
